# ReceiptGraphKIE: LayoutLMv3 with Symbolic Relation-GATv2 and Word-Level CRF

This notebook trains and evaluates a graph-enhanced key information extraction model on the CORD receipt dataset. The architecture combines pretrained LayoutLMv3 representations, a two-layer relation-aware GATv2, hidden-state fusion, separate base and fusion classifiers, and a word-level CRF.

Each receipt is represented as a symbolic word graph. Nodes correspond to words, while typed edges encode exact line membership, cross-line column continuity, directional geometry, and local fallback proximity. The graph branch performs relation-aware message passing and contributes a fixed-scale residual to the LayoutLMv3 word representations before structured CRF decoding.

The evaluation protocol includes:

- Five independent runs with seeds `13`, `42`, `2026`, `7`, and `123`.
- Fresh initialization from pretrained LayoutLMv3 plus randomly initialized graph and task heads for every seed.
- Fixed graph scale `0.50`, base auxiliary weight `0.35`, and early-stopping patience `6`.
- Checkpoint selection based exclusively on development-set Entity Macro F1 in the original graph mode.
- Four development-set graph conditions: `original`, `shuffled`, `self_loop_only`, and `graph_off`.
- Test evaluation only after all five training runs and development ablations are complete.
- Mean ± sample standard deviation reporting, attention diagnostics, document-level predictions, and absolute document bootstrap intervals.

The primary metric is macro F1 over 18 semantic entity classes, excluding the background label `O`.

## 1. Kaggle Runtime Setup and Environment Validation

This section installs only missing dependencies, imports the required machine-learning and graph-processing libraries, verifies CUDA availability, locates the CORD dataset, and initializes the experiment workspace. The existing Kaggle PyTorch installation is retained to maintain CUDA compatibility.

In [1]:
import importlib.util
import subprocess
import sys

REQUIRED = {
    "torch_geometric": "torch-geometric>=2.4,<3",
    "torchcrf": "pytorch-crf>=0.7.2,<1",
    "transformers": "transformers>=4.30,<6",
    "sklearn": "scikit-learn>=1.2,<2",
}

for import_name, package in REQUIRED.items():
    if importlib.util.find_spec(import_name) is None:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])

print("Dependencies are ready. Restart the kernel only if Kaggle requests it.")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 23.2 MB/s eta 0:00:00
Dependencies are ready. Restart the kernel only if Kaggle requests it.

In [2]:
import gc
import hashlib
import json
import math
import os
import platform
import random
import shutil
import time
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import sklearn
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch_geometric
import transformers
from PIL import Image
from sklearn.metrics import classification_report, confusion_matrix, f1_score, precision_recall_fscore_support
from scipy.stats import t as student_t
from torch.optim import AdamW
from torch.utils.data import DataLoader, Dataset, WeightedRandomSampler
from torch_geometric.data import Batch, Data
from torch_geometric.nn import GATv2Conv
from torchcrf import CRF
from tqdm.auto import tqdm
from transformers import LayoutLMv3Model, LayoutLMv3Processor, get_linear_schedule_with_warmup

assert torch.cuda.is_available(), "Hãy bật GPU trong Kaggle trước khi train."

print("Runtime: Kaggle | Python:", platform.python_version())
print("PyTorch:", torch.__version__)
print("CUDA:", torch.version.cuda)
print("GPU:", torch.cuda.get_device_name(0))
print("Transformers:", transformers.__version__)
print("PyG:", torch_geometric.__version__)
print("scikit-learn:", sklearn.__version__)

Runtime: Kaggle | Python: 3.12.13
PyTorch: 2.10.0+cu128
CUDA: 12.8
GPU: Tesla T4
Transformers: 5.0.0
PyG: 2.8.0.post1
scikit-learn: 1.6.1

## 2. Experimental Configuration and Evaluation Protocol

This section defines the architecture, optimization schedule, regularization, graph parameters, reproducibility controls, and artifact paths.

The model is trained exactly five times using seeds `13`, `42`, `2026`, `7`, and `123`. Every run uses the same fixed configuration: two Relation-GATv2 layers, graph scale `0.50`, base auxiliary weight `0.35`, and early-stopping patience `6`. No hyperparameter sweep is performed within this experiment.

Each seed starts from the pretrained `microsoft/layoutlmv3-base` checkpoint with independently initialized graph, fusion, classification, and CRF parameters. Development Entity Macro F1 in the original graph mode is the sole checkpoint-selection criterion.

In [3]:
@dataclass(frozen=True)
class Config:
    profile: str = "paper"
    model_id: str = "microsoft/layoutlmv3-base"
    model_revision: str = "main"
    max_length: int = 512
    batch_size: int = 2
    grad_accum_steps: int = 2
    num_workers: int = 2

    backbone_lr: float = 1e-5
    head_lr: float = 1e-4
    graph_lr: float = 2e-4
    weight_decay: float = 0.01
    warmup_ratio: float = 0.10
    max_epochs: int = 14
    patience: int = 6
    min_delta: float = 1e-4
    freeze_backbone_epochs: int = 1
    lm_dropout: float = 0.30
    gat_attention_dropout: float = 0.10
    graph_dropout: float = 0.10
    fusion_dropout: float = 0.10
    gat_layers: int = 2
    gat_heads: int = 4
    gat_edge_hidden: int = 64
    gat_ffn_multiplier: int = 1
    gat_residual_scale: float = 0.50
    spatial_input_scale: float = 0.10
    relation_types: int = 7
    edge_dim: int = 18
    edge_dropout: float = 0.00

    fixed_graph_alpha: float = 0.50
    base_aux_weight: float = 0.35
    graph_branch_dropout: float = 0.10
    max_graph_neighbors: int = 8
    graph_shuffle_seed: int = 1729
    column_center_threshold: float = 0.10
    column_overlap_threshold: float = 0.20

    crf_weight: float = 0.65
    focal_gamma: float = 2.0
    knn_k: int = 2
    use_rare_document_sampler: bool = True
    rare_sampler_power: float = 0.50
    rare_sampler_max_weight: float = 2.50
    class_balance_beta: float = 0.999
    class_weight_cap: float = 3.0
    use_amp: bool = True
    keep_all_checkpoints: bool = True
    keep_nonselected_alpha_checkpoints: bool = False
    bootstrap_repetitions: int = 10000
    track_epoch_graph_off: bool = True
    artifact_dir: str = "/kaggle/working/receipt_kie_five_seed_retrain_artifacts"


CFG = Config()
SEEDS = [13, 42, 2026, 7, 123]
MAX_EPOCHS = CFG.max_epochs
PATIENCE = CFG.patience
SELECTED_ALPHA = CFG.fixed_graph_alpha
SELECTED_BASE_AUX = CFG.base_aux_weight
MODEL_NAME = "layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf"
DEVICE = torch.device("cuda")
ARTIFACT_DIR = Path(CFG.artifact_dir)
ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

print(
    "Five-seed retrain protocol:",
    "| seeds:", SEEDS,
    "| graph alpha:", SELECTED_ALPHA,
    "| base auxiliary weight:", SELECTED_BASE_AUX,
    "| patience:", PATIENCE,
    "| train runs:", len(SEEDS),
    "| initialization: pretrained LayoutLMv3 + random heads/graph",
)

Five-seed retrain protocol: | seeds: [13, 42, 2026, 7, 123] | graph alpha: 0.5 | base auxiliary weight: 0.35 | patience: 6 | train runs: 5 | initialization: pretrained LayoutLMv3 + random heads/graph

In [4]:
def set_seed(seed: int) -> None:
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def find_cord_root() -> Path:
    candidates = [Path("CORD1000/CORD/CORD")]
    kaggle_input = Path("/kaggle/input")
    if kaggle_input.exists():
        candidates.extend(path.parent.parent for path in kaggle_input.rglob("train/json"))
    for root in candidates:
        if all(
            (root / split / "json").is_dir() and (root / split / "image").is_dir()
            for split in ("train", "dev", "test")
        ):
            return root.resolve()
    raise FileNotFoundError(
        "Không tìm thấy CORD root có train/dev/test/{image,json}. "
        "Hãy attach dataset CORD-1000 vào Kaggle Notebook."
    )


set_seed(SEEDS[0])
CORD_ROOT = find_cord_root()
print("CORD root:", CORD_ROOT)

CORD root: /kaggle/input/datasets/lonelvino/cord-1000/CORD/CORD

## 3. Label Schema and Dataset Audit

This section maps CORD annotations to 18 receipt entity classes and the background class `O`. It validates image–annotation pairing for every split and summarizes document counts, word counts, and class frequencies.

Entity Macro F1 over the 18 non-background classes is the primary metric. Entity Micro F1, weighted F1, precision, recall, per-class support, and graph-specific diagnostics are retained for complementary analysis.

In [5]:
CORD_CATEGORY_TO_LABEL = {
    "menu.nm": "S-MENU_NM", "menu.sub_nm": "S-MENU_NM",
    "menu.cnt": "S-MENU_CNT", "menu.sub_cnt": "S-MENU_CNT",
    "menu.num": "S-MENU_NUM", "menu.unitprice": "S-MENU_UNITPRICE",
    "menu.price": "S-MENU_PRICE", "menu.sub_price": "S-MENU_PRICE",
    "menu.discountprice": "S-MENU_DISCOUNT_PRICE",
    "sub_total.subtotal_price": "S-SUBTOTAL",
    "sub_total.discount_price": "S-DISCOUNT",
    "sub_total.tax_price": "S-TAX", "sub_total.service_price": "S-SERVICE",
    "total.total_price": "S-TOTAL", "total.cashprice": "S-CASH",
    "total.changeprice": "S-CHANGE", "total.creditcardprice": "S-CARD_PAYMENT",
    "total.emoneyprice": "S-EMONEY_PAYMENT", "total.menuqty_cnt": "S-MENUQTY_CNT",
    "total.menutype_cnt": "S-MENUTYPE_CNT",
    "sub_total.etc": "S-OTHER", "total.total_etc": "S-OTHER",
    "menu.etc": "S-OTHER", "menu.sub_etc": "S-OTHER",
    "menu.itemsubtotal": "O", "menu.vatyn": "O",
    "sub_total.othersvc_price": "O", "void_menu.nm": "O",
    "void_menu.price": "O", "menu.sub_unitprice": "O",
}

LABELS = [
    "O", "S-MENU_NM", "S-MENU_CNT", "S-MENU_NUM", "S-MENU_UNITPRICE",
    "S-MENU_PRICE", "S-MENU_DISCOUNT_PRICE", "S-SUBTOTAL", "S-DISCOUNT",
    "S-TAX", "S-SERVICE", "S-TOTAL", "S-CASH", "S-CHANGE",
    "S-CARD_PAYMENT", "S-EMONEY_PAYMENT", "S-MENUQTY_CNT",
    "S-MENUTYPE_CNT", "S-OTHER",
]
ID2LABEL = dict(enumerate(LABELS))
LABEL2ID = {label: idx for idx, label in ID2LABEL.items()}
ENTITY_IDS = list(range(1, len(LABELS)))
NUM_LABELS = len(LABELS)


def dataset_audit(root: Path) -> pd.DataFrame:
    rows = []
    for split in ("train", "dev", "test"):
        json_files = sorted((root / split / "json").glob("*.json"))
        image_files = sorted((root / split / "image").glob("*.png"))
        json_stems, image_stems = {p.stem for p in json_files}, {p.stem for p in image_files}
        counts = Counter()
        for path in json_files:
            data = json.loads(path.read_text(encoding="utf-8"))
            for line in data.get("valid_line", []):
                mapped = CORD_CATEGORY_TO_LABEL.get(line.get("category", ""), "O")
                counts[mapped] += len(line.get("words", []))
        rows.append({
            "split": split, "json": len(json_files), "images": len(image_files),
            "missing_images": len(json_stems - image_stems),
            "missing_json": len(image_stems - json_stems),
            "words": sum(counts.values()), **counts,
        })
    return pd.DataFrame(rows).fillna(0)


audit_df = dataset_audit(CORD_ROOT)
display(audit_df)
assert (audit_df[["missing_images", "missing_json"]].to_numpy() == 0).all(), "Dataset thiếu cặp image/json."

,split,json,images,missing_images,missing_json,words,S-MENU_CNT,S-MENU_NM,S-MENU_PRICE,S-SUBTOTAL,...,S-CHANGE,S-MENUTYPE_CNT,S-MENUQTY_CNT,S-DISCOUNT,S-MENU_UNITPRICE,S-CARD_PAYMENT,S-MENU_NUM,S-MENU_DISCOUNT_PRICE,S-EMONEY_PAYMENT,O
0,train,800,800,0,0,19371,2126,5995,2236,1187,...,1044,105,513,164,629,326,94,355,115,31
1,dev,100,100,0,0,2186,246,686,241,151,...,135,8,50,11,52,34,4,18,10,3
2,test,100,100,0,0,2356,246,740,268,145,...,120,17,67,16,69,51,11,30,4,6

## 4. Symbolic Graph Construction and Word-Level Inputs

This section builds one graph for each receipt and prepares the corresponding LayoutLMv3 inputs.

Each graph node represents a CORD word. The graph uses seven relation types:

- `SAME_LINE` connects words that share the same `valid_line` identifier.
- `NEXT_LINE_COLUMN` connects aligned words across consecutive lines using horizontal overlap and center-distance constraints.
- `LEFT`, `RIGHT`, `ABOVE`, and `BELOW` encode directional spatial relationships.
- `KNN` supplies local fallback edges when symbolic and directional relations do not fill the neighbor budget.

Every edge also carries continuous geometric attributes derived from relative position, distance, size, overlap, and orientation. Graph construction uses document structure and geometry only; entity labels are never used to create edges.

CORD text and normalized bounding boxes are encoded with `apply_ocr=False`. LayoutLMv3 subtokens are mapped back to words, truncated words are removed consistently from labels and graphs, and variable-size graphs are batched with PyTorch Geometric.

In [6]:
def quad_to_bbox(quad, width, height):
    xs = [quad[f"x{i}"] for i in range(1, 5)]
    ys = [quad[f"y{i}"] for i in range(1, 5)]
    x0, y0, x1, y1 = int(min(xs)), int(min(ys)), int(max(xs)), int(max(ys))
    x0, y0 = max(0, min(x0, width - 1)), max(0, min(y0, height - 1))
    x1, y1 = max(x0 + 1, min(x1, width)), max(y0 + 1, min(y1, height))
    return x0, y0, x1, y1


def build_records(root: Path, split: str):
    records = []
    for json_path in tqdm(sorted((root / split / "json").glob("*.json")), desc=f"Parse {split}"):
        data = json.loads(json_path.read_text(encoding="utf-8"))
        width = int(data["meta"]["image_size"]["width"])
        height = int(data["meta"]["image_size"]["height"])
        image_path = root / split / "image" / f"{json_path.stem}.png"
        words = []
        for line_index, line in enumerate(data.get("valid_line", [])):
            label = CORD_CATEGORY_TO_LABEL.get(line.get("category", ""), "O")
            for word in line.get("words", []):
                text = word.get("text", "").strip()
                if text:
                    raw_row_id = word.get("row_id")
                    line_id = (
                        f"row_{raw_row_id}"
                        if raw_row_id is not None
                        else f"valid_line_{line_index}"
                    )
                    words.append({
                        "text": text,
                        "box": quad_to_bbox(word["quad"], width, height),
                        "label": label,
                        "line_id": line_id,
                    })
        words.sort(key=lambda item: (item["box"][1], item["box"][0]))
        if words and image_path.exists():
            records.append({
                "id": json_path.stem,
                "image_path": image_path,
                "size": (width, height),
                "words": words,
            })
    return records


train_records = build_records(CORD_ROOT, "train")
dev_records = build_records(CORD_ROOT, "dev")
test_records = build_records(CORD_ROOT, "test")
print("Documents:", len(train_records), len(dev_records), len(test_records))

Parse train:   0%|          | 0/800 [00:00<?, ?it/s]

Parse dev:   0%|          | 0/100 [00:00<?, ?it/s]

Parse test:   0%|          | 0/100 [00:00<?, ?it/s]

Documents: 800 100 100

In [7]:
def normalize_box(box, width, height):
    x0, y0, x1, y1 = box
    values = [1000 * x0 / width, 1000 * y0 / height, 1000 * x1 / width, 1000 * y1 / height]
    return [max(0, min(1000, int(v))) for v in values]


def vertical_overlap_ratio(a, b):
    _, ay0, _, ay1 = a
    _, by0, _, by1 = b
    overlap = max(0.0, min(ay1, by1) - max(ay0, by0))
    return overlap / max(min(ay1 - ay0, by1 - by0), 1.0)


def horizontal_overlap_ratio(a, b):
    ax0, _, ax1, _ = a
    bx0, _, bx1, _ = b
    overlap = max(0.0, min(ax1, bx1) - max(ax0, bx0))
    return overlap / max(min(ax1 - ax0, bx1 - bx0), 1.0)


def same_line_geometry(a, b, threshold=0.5):
    return vertical_overlap_ratio(a, b) >= threshold


def horizontally_aligned(a, b, image_width, threshold=0.10):
    ax0, _, ax1, _ = a
    bx0, _, bx1, _ = b
    center_distance = abs((ax0 + ax1 - bx0 - bx1) / 2) / image_width
    return (
        horizontal_overlap_ratio(a, b) >= CFG.column_overlap_threshold
        or center_distance <= threshold
    )


RELATION_TO_ID = {
    "KNN": 0,
    "LEFT": 1,
    "RIGHT": 2,
    "ABOVE": 3,
    "BELOW": 4,
    "SAME_LINE": 5,
    "NEXT_LINE_COLUMN": 6,
}
INVERSE_RELATION = {
    "KNN": "KNN",
    "LEFT": "RIGHT",
    "RIGHT": "LEFT",
    "ABOVE": "BELOW",
    "BELOW": "ABOVE",
    "SAME_LINE": "SAME_LINE",
    "NEXT_LINE_COLUMN": "NEXT_LINE_COLUMN",
}
assert len(RELATION_TO_ID) == CFG.relation_types
assert CFG.edge_dim == 11 + CFG.relation_types


def build_spatial_graph(words, image_size, k=2):
    width, height = image_size
    boxes = np.asarray([item["box"] for item in words], dtype=np.float32)
    n = len(words)
    centers = np.column_stack((
        (boxes[:, 0] + boxes[:, 2]) / (2 * width),
        (boxes[:, 1] + boxes[:, 3]) / (2 * height),
    ))
    widths = (boxes[:, 2] - boxes[:, 0]) / width
    heights = (boxes[:, 3] - boxes[:, 1]) / height
    edge_relations = defaultdict(set)

    def connect(i, j, relation):
        if i == j:
            return
        edge_relations[(i, j)].add(RELATION_TO_ID[relation])
        edge_relations[(j, i)].add(RELATION_TO_ID[INVERSE_RELATION[relation]])

    line_to_nodes = defaultdict(list)
    for index, word in enumerate(words):
        line_to_nodes[word["line_id"]].append(index)
    ordered_lines = sorted(
        line_to_nodes.values(),
        key=lambda nodes: float(np.mean(centers[nodes, 1])),
    )

    for nodes in ordered_lines:
        ordered_nodes = sorted(nodes, key=lambda index: centers[index, 0])
        for left_node, right_node in zip(ordered_nodes[:-1], ordered_nodes[1:]):
            connect(left_node, right_node, "SAME_LINE")
            connect(left_node, right_node, "RIGHT")

    for upper_nodes, lower_nodes in zip(ordered_lines[:-1], ordered_lines[1:]):
        for i in upper_nodes:
            candidates = [
                j for j in lower_nodes
                if horizontally_aligned(
                    boxes[i], boxes[j], width, CFG.column_center_threshold
                )
            ]
            if candidates:
                j = min(candidates, key=lambda node: abs(centers[node, 0] - centers[i, 0]))
                connect(i, j, "NEXT_LINE_COLUMN")
                connect(i, j, "BELOW")

    if n > 1:
        for i in range(n):
            left = [
                j for j in range(n)
                if centers[j, 0] < centers[i, 0]
                and words[j]["line_id"] == words[i]["line_id"]
            ]
            right = [
                j for j in range(n)
                if centers[j, 0] > centers[i, 0]
                and words[j]["line_id"] == words[i]["line_id"]
            ]
            if left:
                connect(i, min(left, key=lambda j: centers[i, 0] - centers[j, 0]), "LEFT")
            if right:
                connect(i, min(right, key=lambda j: centers[j, 0] - centers[i, 0]), "RIGHT")

        for i in range(n):
            current = {dst for src, dst in edge_relations if src == i}
            free_slots = max(CFG.max_graph_neighbors - len(current), 0)
            if free_slots == 0:
                continue
            distances = np.linalg.norm(centers - centers[i], axis=1)
            candidates = [
                int(j) for j in np.argsort(distances)
                if j != i and int(j) not in current
            ]
            for j in candidates[:min(k, free_slots)]:
                connect(i, j, "KNN")

    symbolic_ids = {
        RELATION_TO_ID["SAME_LINE"],
        RELATION_TO_ID["NEXT_LINE_COLUMN"],
    }
    directional_ids = {
        RELATION_TO_ID["LEFT"], RELATION_TO_ID["RIGHT"],
        RELATION_TO_ID["ABOVE"], RELATION_TO_ID["BELOW"],
    }
    bounded_relations = {}
    for i in range(n):
        destinations = [j for src, j in edge_relations if src == i]

        def priority(j):
            relations = edge_relations[(i, j)]
            if relations & symbolic_ids:
                relation_priority = 0
            elif relations & directional_ids:
                relation_priority = 1
            else:
                relation_priority = 2
            return relation_priority, float(np.linalg.norm(centers[j] - centers[i]))

        destinations.sort(key=priority)
        for j in destinations[:CFG.max_graph_neighbors]:
            bounded_relations[(i, j)] = edge_relations[(i, j)]

    src, dst, features = [], [], []
    for (i, j), relation_ids in sorted(bounded_relations.items()):
        dx = float(centers[j, 0] - centers[i, 0])
        dy = float(centers[j, 1] - centers[i, 1])
        distance = float(np.hypot(dx, dy))
        angle = math.atan2(dy, dx)
        log_width_ratio = float(np.clip(
            np.log(max(widths[j], 1e-6) / max(widths[i], 1e-6)), -4, 4
        ))
        log_height_ratio = float(np.clip(
            np.log(max(heights[j], 1e-6) / max(heights[i], 1e-6)), -4, 4
        ))
        log_area_ratio = float(np.clip(
            np.log(max(widths[j] * heights[j], 1e-6) / max(widths[i] * heights[i], 1e-6)),
            -4, 4,
        ))
        relation_one_hot = [
            float(rel_id in relation_ids) for rel_id in range(CFG.relation_types)
        ]
        src.append(i)
        dst.append(j)
        features.append([
            dx, dy, distance,
            log_width_ratio, log_height_ratio, log_area_ratio,
            vertical_overlap_ratio(boxes[i], boxes[j]),
            horizontal_overlap_ratio(boxes[i], boxes[j]),
            float(words[i]["line_id"] == words[j]["line_id"]),
            math.sin(angle), math.cos(angle),
            *relation_one_hot,
        ])

    has_edges = bool(bounded_relations)
    edge_index = (
        torch.tensor([src, dst], dtype=torch.long)
        if has_edges else torch.empty((2, 0), dtype=torch.long)
    )
    edge_attr = (
        torch.tensor(features, dtype=torch.float32)
        if has_edges else torch.empty((0, CFG.edge_dim), dtype=torch.float32)
    )
    spatial = torch.tensor(np.column_stack((centers, widths, heights)), dtype=torch.float32)
    assert edge_attr.shape[1] == CFG.edge_dim
    return Data(edge_index=edge_index, edge_attr=edge_attr, spatial_pos=spatial, num_nodes=n)

In [8]:
processor = LayoutLMv3Processor.from_pretrained(
    CFG.model_id, revision=CFG.model_revision, apply_ocr=False
)


class CORDWordDataset(Dataset):
    def __init__(self, records):
        self.records = records

    def __len__(self):
        return len(self.records)

    def __getitem__(self, index):
        record = self.records[index]
        width, height = record["size"]
        image = Image.open(record["image_path"]).convert("RGB")
        texts = [item["text"] for item in record["words"]]
        boxes = [normalize_box(item["box"], width, height) for item in record["words"]]
        encoding = processor(
            image, texts, boxes=boxes, truncation=True, max_length=CFG.max_length,
            padding="max_length", return_tensors="pt",
        )
        word_ids = encoding.word_ids(batch_index=0)
        active_ids = sorted({wid for wid in word_ids if wid is not None})
        ranges = []
        for wid in active_ids:
            positions = [pos for pos, current in enumerate(word_ids) if current == wid]
            ranges.append((positions[0], positions[-1] + 1))
        active_words = [record["words"][wid] for wid in active_ids]
        labels = torch.tensor([LABEL2ID[item["label"]] for item in active_words], dtype=torch.long)
        graph = build_spatial_graph(active_words, record["size"], CFG.knn_k)
        return {
            "id": record["id"],
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "bbox": encoding["bbox"].squeeze(0),
            "pixel_values": encoding["pixel_values"].squeeze(0),
            "word_ranges": ranges, "word_labels": labels, "graph": graph,
        }


def collate_fn(samples):
    tensor_keys = ("input_ids", "attention_mask", "bbox", "pixel_values")
    batch = {key: torch.stack([sample[key] for sample in samples]) for key in tensor_keys}
    max_words = max(len(sample["word_labels"]) for sample in samples)
    labels = torch.zeros((len(samples), max_words), dtype=torch.long)
    mask = torch.zeros((len(samples), max_words), dtype=torch.bool)
    for i, sample in enumerate(samples):
        size = len(sample["word_labels"])
        labels[i, :size] = sample["word_labels"]
        mask[i, :size] = True
    batch.update({
        "ids": [sample["id"] for sample in samples],
        "word_ranges": [sample["word_ranges"] for sample in samples],
        "word_labels": labels, "word_mask": mask,
        "graphs": Batch.from_data_list([sample["graph"] for sample in samples]),
    })
    return batch


train_ds, dev_ds, test_ds = map(CORDWordDataset, (train_records, dev_records, test_records))


def build_document_sample_weights(records):
    document_labels = [
        {LABEL2ID[word["label"]] for word in record["words"] if word["label"] != "O"}
        for record in records
    ]
    document_frequency = Counter(label for labels in document_labels for label in labels)
    weights = []
    for labels in document_labels:
        rarity = [
            (len(records) / max(document_frequency[label], 1)) ** CFG.rare_sampler_power
            for label in labels
        ]
        weights.append(min(max(rarity, default=1.0), CFG.rare_sampler_max_weight))
    return torch.tensor(weights, dtype=torch.double), document_frequency


train_sample_weights, train_document_frequency = build_document_sample_weights(train_records)
print("Rare-document sampler:", CFG.use_rare_document_sampler,
      "| weight range:", f"{train_sample_weights.min():.2f}–{train_sample_weights.max():.2f}")


def make_loaders(seed):
    loader_generator = torch.Generator().manual_seed(seed)
    common = dict(batch_size=CFG.batch_size, num_workers=CFG.num_workers,
                  pin_memory=True, collate_fn=collate_fn,
                  persistent_workers=CFG.num_workers > 0)
    if CFG.use_rare_document_sampler:
        sampler_generator = torch.Generator().manual_seed(seed)
        sampler = WeightedRandomSampler(
            train_sample_weights, num_samples=len(train_ds), replacement=True,
            generator=sampler_generator,
        )
        train_loader = DataLoader(train_ds, sampler=sampler, generator=loader_generator, **common)
    else:
        train_loader = DataLoader(train_ds, shuffle=True, generator=loader_generator, **common)
    return (
        train_loader,
        DataLoader(dev_ds, shuffle=False, **common),
        DataLoader(test_ds, shuffle=False, **common),
    )

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

preprocessor_config.json:   0%|          | 0.00/275 [00:00<?, ?B/s]

The image processor of type `LayoutLMv3ImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

config.json:   0%|          | 0.00/856 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

Rare-document sampler: True | weight range: 1.05–2.50

## 5. Two-Layer Relation-GATv2, Split Heads, and Hidden Fusion

This section defines the hybrid architecture.

LayoutLMv3 first produces one contextual representation per word. A normalized graph input combines these representations with a small projected spatial signal. Two Relation-GATv2 blocks then perform edge-conditioned message passing. Each block contains pre-normalization, a learned edge encoder, multi-head GATv2 attention, residual connections, and a feed-forward residual sublayer.

The graph branch models a correction rather than replacing the language-layout representation. The change introduced by message passing is projected and fused with the original LayoutLMv3 word state through a fixed-scale residual with `alpha = 0.50`. The final fusion projection is zero-initialized so training begins from the non-graph representation.

Separate linear classifiers are used for the base and fused branches. This prevents the auxiliary base objective from directly shifting the decision boundary of the graph-enhanced classifier. A shared word-level CRF provides structured decoding for both paths. Attention entropy, attention variance, residual magnitude, and residual-to-base norm ratio are recorded as graph diagnostics.

In [9]:
class WordModelBase(nn.Module):
    def __init__(self):
        super().__init__()
        self.backbone = LayoutLMv3Model.from_pretrained(CFG.model_id, revision=CFG.model_revision)
        self.hidden_size = self.backbone.config.hidden_size
        self.crf = CRF(NUM_LABELS, batch_first=True)

    @staticmethod
    def aggregate_words(token_embeddings, ranges_per_doc):
        docs = []
        for batch_index, ranges in enumerate(ranges_per_doc):
            docs.append(torch.stack([
                token_embeddings[batch_index, start:end].mean(dim=0)
                for start, end in ranges
            ]))
        return docs

    @staticmethod
    def pad_documents(doc_embeddings, max_words):
        hidden = doc_embeddings[0].shape[-1]
        padded = doc_embeddings[0].new_zeros((len(doc_embeddings), max_words, hidden))
        for i, embeddings in enumerate(doc_embeddings):
            padded[i, :len(embeddings)] = embeddings
        return padded

    def encode(self, batch):
        outputs = self.backbone(
            input_ids=batch["input_ids"].to(DEVICE),
            attention_mask=batch["attention_mask"].to(DEVICE),
            bbox=batch["bbox"].to(DEVICE),
            pixel_values=batch["pixel_values"].to(DEVICE),
        )
        text_length = batch["input_ids"].shape[1]
        return self.aggregate_words(outputs.last_hidden_state[:, :text_length], batch["word_ranges"])

    def branch_loss(self, emissions, labels, mask, class_weights):
        emissions_fp32 = emissions.float()
        crf_loss = -self.crf(
            emissions_fp32, labels, mask=mask, reduction="token_mean"
        )
        logits, targets = emissions_fp32[mask], labels[mask]
        ce = F.cross_entropy(logits, targets, weight=class_weights, reduction="none")
        pt = torch.softmax(logits, dim=-1).gather(1, targets[:, None]).squeeze(1)
        focal_loss = (((1 - pt) ** CFG.focal_gamma) * ce).mean()
        return CFG.crf_weight * crf_loss + (1 - CFG.crf_weight) * focal_loss

    def loss(self, emissions, labels, mask, class_weights):
        return self.branch_loss(emissions, labels, mask, class_weights)

    def decode(self, emissions, mask):
        return self.crf.decode(emissions.float(), mask=mask)


class RelationEdgeGATBlock(nn.Module):
    def __init__(self, hidden_size):
        super().__init__()
        assert hidden_size % CFG.gat_heads == 0
        self.pre_norm = nn.LayerNorm(hidden_size)
        self.edge_encoder = nn.Sequential(
            nn.LayerNorm(CFG.edge_dim),
            nn.Linear(CFG.edge_dim, CFG.gat_edge_hidden),
            nn.GELU(),
            nn.Linear(CFG.gat_edge_hidden, CFG.gat_edge_hidden),
        )
        self.conv = GATv2Conv(
            hidden_size, hidden_size // CFG.gat_heads, heads=CFG.gat_heads,
            concat=True, dropout=CFG.gat_attention_dropout,
            edge_dim=CFG.gat_edge_hidden, add_self_loops=True,
            share_weights=True,
        )
        ffn_hidden = CFG.gat_ffn_multiplier * hidden_size
        self.ffn_norm = nn.LayerNorm(hidden_size)
        self.ffn = nn.Sequential(
            nn.Linear(hidden_size, ffn_hidden), nn.GELU(),
            nn.Dropout(CFG.graph_dropout), nn.Linear(ffn_hidden, hidden_size),
        )
        self.dropout = nn.Dropout(CFG.graph_dropout)
        self.reset_attention_diagnostics()

    def reset_attention_diagnostics(self):
        self._attention_entropy_sum = 0.0
        self._attention_variance_sum = 0.0
        self._attention_batches = 0

    def attention_diagnostics(self):
        if self._attention_batches == 0:
            return {
                "attention_entropy": float("nan"),
                "attention_variance": float("nan"),
            }
        return {
            "attention_entropy": self._attention_entropy_sum / self._attention_batches,
            "attention_variance": self._attention_variance_sum / self._attention_batches,
        }

    def drop_edges(self, edge_index, edge_attr):
        if not self.training or CFG.edge_dropout <= 0 or edge_index.shape[1] == 0:
            return edge_index, edge_attr
        keep = torch.rand(edge_index.shape[1], device=edge_index.device) >= CFG.edge_dropout
        if not bool(keep.any()):
            keep[torch.randint(edge_index.shape[1], (1,), device=edge_index.device)] = True
        return edge_index[:, keep], edge_attr[keep]

    def record_attention(self, attention_edge_index, alpha, num_nodes):
        alpha_fp32 = alpha.detach().float().clamp_min(1e-8)
        destinations = attention_edge_index[1]
        entropy_terms = -alpha_fp32 * alpha_fp32.log()
        node_entropy = alpha_fp32.new_zeros((num_nodes, alpha_fp32.shape[1]))
        node_entropy.index_add_(0, destinations, entropy_terms)
        degree = torch.bincount(destinations, minlength=num_nodes).float()
        valid = degree > 1
        if bool(valid.any()):
            normalizer = degree[valid].log().unsqueeze(-1).clamp_min(1e-8)
            normalized_entropy = node_entropy[valid] / normalizer
            entropy_value = normalized_entropy.mean().item()
        else:
            entropy_value = 0.0
        self._attention_entropy_sum += entropy_value
        self._attention_variance_sum += alpha_fp32.var(unbiased=False).item()
        self._attention_batches += 1

    def forward(self, x, edge_index, edge_attr):
        edge_index, edge_attr = self.drop_edges(edge_index, edge_attr)
        normalized_x = self.pre_norm(x)
        encoded_edge_attr = self.edge_encoder(edge_attr)
        if self.training:
            message = self.conv(normalized_x, edge_index, encoded_edge_attr)
        else:
            message, (attention_edge_index, alpha) = self.conv(
                normalized_x, edge_index, encoded_edge_attr,
                return_attention_weights=True,
            )
            self.record_attention(attention_edge_index, alpha, x.shape[0])
        x = x + CFG.gat_residual_scale * self.dropout(message)
        ffn_message = self.ffn(self.ffn_norm(x))
        return x + CFG.gat_residual_scale * self.dropout(ffn_message)


class LayoutLMv3SymbolicRelationGATFusionCRF(WordModelBase):
    def __init__(self, graph_alpha, base_aux_weight):
        super().__init__()
        hidden = self.hidden_size
        self.register_buffer("_graph_alpha", torch.tensor(float(graph_alpha)))
        self.base_aux_weight = float(base_aux_weight)
        self.spatial_proj = nn.Sequential(
            nn.Linear(4, hidden // 2), nn.GELU(), nn.Linear(hidden // 2, hidden)
        )
        self.graph_input_norm = nn.LayerNorm(hidden)
        self.gat = nn.ModuleList([
            RelationEdgeGATBlock(hidden) for _ in range(CFG.gat_layers)
        ])
        self.graph_proj = nn.Sequential(
            nn.Linear(hidden, hidden), nn.GELU(),
            nn.Dropout(CFG.graph_dropout), nn.Linear(hidden, hidden),
        )
        self.fusion_proj = nn.Sequential(
            nn.Linear(2 * hidden, hidden), nn.GELU(),
            nn.Dropout(CFG.fusion_dropout), nn.Linear(hidden, hidden),
        )
        self.fusion_norm = nn.LayerNorm(hidden)
        self.dropout = nn.Dropout(CFG.lm_dropout)
        self.base_classifier = nn.Linear(hidden, NUM_LABELS)
        self.classifier = nn.Linear(hidden, NUM_LABELS)
        nn.init.zeros_(self.fusion_proj[-1].weight)
        nn.init.zeros_(self.fusion_proj[-1].bias)
        self._current_base_emissions = None
        self.graph_mode = "original"
        self.reset_graph_diagnostics()

    @property
    def graph_alpha(self):
        return float(self._graph_alpha.item())

    def set_backbone_trainable(self, trainable):
        for parameter in self.backbone.parameters():
            parameter.requires_grad = trainable
        if not trainable:
            self.backbone.eval()

    def set_graph_mode(self, mode):
        valid = {"original", "shuffled", "self_loop_only", "graph_off"}
        if mode not in valid:
            raise ValueError(f"Unknown graph mode: {mode}")
        self.graph_mode = mode

    @staticmethod
    def shuffled_edges(graph):
        edge_index = graph.edge_index
        if edge_index.shape[1] == 0:
            return edge_index, graph.edge_attr
        node_map = torch.arange(graph.num_nodes, device=edge_index.device)
        boundaries = graph.ptr.detach().cpu().tolist()
        for doc_index, (start, end) in enumerate(zip(boundaries[:-1], boundaries[1:])):
            size = end - start
            generator = torch.Generator().manual_seed(
                CFG.graph_shuffle_seed + 1009 * size + doc_index
            )
            permutation = torch.randperm(size, generator=generator).to(edge_index.device) + start
            node_map[start:end] = permutation
        return node_map[edge_index], graph.edge_attr

    def ablation_edges(self, graph):
        if self.graph_mode == "original":
            return graph.edge_index, graph.edge_attr
        if self.graph_mode == "shuffled":
            return self.shuffled_edges(graph)
        if self.graph_mode == "self_loop_only":
            return (
                torch.empty((2, 0), dtype=torch.long, device=graph.edge_index.device),
                torch.empty((0, CFG.edge_dim), dtype=graph.edge_attr.dtype, device=graph.edge_attr.device),
            )
        raise RuntimeError("graph_off does not request graph edges")

    def reset_graph_diagnostics(self):
        self._base_norm_sum = 0.0
        self._residual_norm_sum = 0.0
        self._diagnostic_token_count = 0
        for layer in self.gat:
            layer.reset_attention_diagnostics()

    def graph_diagnostics(self):
        diagnostics = {"graph_alpha": self.graph_alpha}
        if self._diagnostic_token_count == 0:
            diagnostics.update({
                "graph_residual_base_ratio": float("nan"),
                "graph_residual_norm": float("nan"),
            })
        else:
            diagnostics.update({
                "graph_residual_base_ratio": (
                    self._residual_norm_sum / max(self._base_norm_sum, 1e-12)
                ),
                "graph_residual_norm": (
                    self._residual_norm_sum / self._diagnostic_token_count
                ),
            })
        for layer_index, layer in enumerate(self.gat, start=1):
            for name, value in layer.attention_diagnostics().items():
                diagnostics[f"layer{layer_index}_{name}"] = value
        return diagnostics

    def loss(self, emissions, labels, mask, class_weights):
        hybrid_loss = self.branch_loss(emissions, labels, mask, class_weights)
        if self._current_base_emissions is None or self.base_aux_weight <= 0:
            return hybrid_loss
        base_loss = self.branch_loss(
            self._current_base_emissions, labels, mask, class_weights
        )
        return (
            hybrid_loss + self.base_aux_weight * base_loss
        ) / (1 + self.base_aux_weight)

    def forward(self, batch):
        lm_docs = self.encode(batch)
        lm_words = torch.cat(lm_docs, dim=0)
        base_flat = self.base_classifier(self.dropout(lm_words))

        base_docs, offset = [], 0
        for lm_doc in lm_docs:
            base_docs.append(base_flat[offset:offset + len(lm_doc)])
            offset += len(lm_doc)
        base_padded = self.pad_documents(base_docs, batch["word_mask"].shape[1])
        self._current_base_emissions = base_padded

        branch_dropped = (
            self.training
            and self.graph_mode == "original"
            and bool(torch.rand((), device=lm_words.device) < CFG.graph_branch_dropout)
        )
        if self.graph_mode == "graph_off" or branch_dropped:
            return base_padded

        graph = batch["graphs"].to(DEVICE)
        edge_index, edge_attr = self.ablation_edges(graph)
        graph_seed = self.graph_input_norm(
            lm_words + CFG.spatial_input_scale * self.spatial_proj(graph.spatial_pos)
        )
        graph_words = graph_seed
        for layer in self.gat:
            graph_words = layer(graph_words, edge_index, edge_attr)

        graph_delta = self.graph_proj(graph_words - graph_seed)
        fusion_residual = self.fusion_proj(torch.cat([lm_words, graph_delta], dim=-1))
        scaled_residual = self.graph_alpha * fusion_residual
        fused_words = self.fusion_norm(lm_words + scaled_residual)
        flat_emissions = self.classifier(self.dropout(fused_words))

        if not self.training:
            detached_base = lm_words.detach().float()
            detached_residual = scaled_residual.detach().float()
            self._base_norm_sum += detached_base.norm(dim=-1).sum().item()
            self._residual_norm_sum += detached_residual.norm(dim=-1).sum().item()
            self._diagnostic_token_count += detached_base.shape[0]

        docs, offset = [], 0
        for lm_doc in lm_docs:
            docs.append(flat_emissions[offset:offset + len(lm_doc)])
            offset += len(lm_doc)
        return self.pad_documents(docs, batch["word_mask"].shape[1])

## 6. Training Objective, Optimization, and Evaluation

The fused branch and auxiliary base branch each use a combination of CRF negative log-likelihood and class-weighted focal cross-entropy. Their losses are combined as:

```text
(fusion_loss + 0.35 × base_loss) / 1.35
```

The auxiliary term maintains a useful LayoutLMv3-only representation while allowing the fused graph path to remain the primary optimization target.

Class weights are computed exclusively from the training split using capped effective-number weighting. The optimizer assigns separate learning rates to the backbone, task heads, and graph modules. Training uses mixed precision, gradient accumulation, gradient clipping, linear warmup and decay, one epoch of backbone freezing, and early stopping with patience `6`.

Checkpoint selection uses development Entity Macro F1 in the `original` graph mode only. Epoch-level graph-off measurements and attention statistics are diagnostic outputs and do not influence early stopping or checkpoint selection.

In [10]:
train_label_counts = Counter(
    LABEL2ID[word["label"]] for record in train_records for word in record["words"]
)
counts = torch.tensor([train_label_counts.get(i, 0) for i in range(NUM_LABELS)], dtype=torch.float32)
beta = CFG.class_balance_beta
effective_counts = (1 - torch.pow(torch.tensor(beta), counts.clamp_min(1))) / (1 - beta)
class_weights = effective_counts.reciprocal()
entity_mean = class_weights[1:].mean()
class_weights = class_weights / entity_mean
class_weights[0] = 1.0
class_weights = class_weights.clamp(max=CFG.class_weight_cap).to(DEVICE)
display(pd.DataFrame({"label": LABELS, "train_words": counts.int(), "weight": class_weights.cpu()}))


def calculate_metrics(golds, preds):
    precision, recall, macro_f1, _ = precision_recall_fscore_support(
        golds, preds, labels=ENTITY_IDS, average="macro", zero_division=0
    )
    return {
        "entity_macro_precision": float(precision),
        "entity_macro_recall": float(recall),
        "entity_macro_f1": float(macro_f1),
        "entity_micro_f1": float(f1_score(golds, preds, labels=ENTITY_IDS, average="micro", zero_division=0)),
        "weighted_f1": float(f1_score(golds, preds, labels=list(range(NUM_LABELS)), average="weighted", zero_division=0)),
    }


@torch.no_grad()
def evaluate(model, loader):
    model.eval()
    if hasattr(model, "reset_graph_diagnostics"):
        model.reset_graph_diagnostics()
    losses, golds, preds = [], [], []
    for batch in tqdm(loader, leave=False, desc="evaluate"):
        labels = batch["word_labels"].to(DEVICE)
        mask = batch["word_mask"].to(DEVICE)
        with torch.amp.autocast(device_type="cuda", enabled=CFG.use_amp):
            emissions = model(batch)
            loss = model.loss(emissions, labels, mask, class_weights)
        losses.append(loss.item())
        paths = model.decode(emissions, mask)
        for i, path in enumerate(paths):
            length = int(mask[i].sum())
            preds.extend(path[:length])
            golds.extend(labels[i, :length].tolist())
    metrics = calculate_metrics(golds, preds)
    metrics["loss"] = float(np.mean(losses))
    if hasattr(model, "graph_diagnostics"):
        metrics.update(model.graph_diagnostics())
    report = classification_report(
        golds, preds, labels=list(range(NUM_LABELS)), target_names=LABELS,
        zero_division=0, output_dict=True,
    )
    return metrics, report, golds, preds


def parameter_groups(model):
    groups = {"backbone": [], "base_head": [], "graph": []}
    for name, parameter in model.named_parameters():
        if name.startswith("backbone."):
            groups["backbone"].append(parameter)
        elif name.startswith(("spatial_proj.", "graph_input_norm.", "gat.", "graph_proj.", "fusion_proj.", "fusion_norm.")):
            groups["graph"].append(parameter)
        else:
            groups["base_head"].append(parameter)
    specs = [
        ("backbone", CFG.backbone_lr, CFG.weight_decay),
        ("base_head", CFG.head_lr, CFG.weight_decay),
        ("graph", CFG.graph_lr, CFG.weight_decay),
    ]
    return [
        {"params": groups[name], "lr": learning_rate, "weight_decay": weight_decay}
        for name, learning_rate, weight_decay in specs if groups[name]
    ]


def train_model(
    model, train_loader, dev_loader, run_name, seed, patience
):
    model.to(DEVICE)
    optimizer = AdamW(parameter_groups(model))
    steps_per_epoch = math.ceil(len(train_loader) / CFG.grad_accum_steps)
    total_steps = steps_per_epoch * MAX_EPOCHS
    scheduler = get_linear_schedule_with_warmup(
        optimizer, int(total_steps * CFG.warmup_ratio), total_steps
    )
    scaler = torch.amp.GradScaler("cuda", enabled=CFG.use_amp)
    checkpoint_path = ARTIFACT_DIR / f"{run_name}_seed{seed}.pt"
    history, best_f1, best_epoch, stale_epochs = [], -1.0, -1, 0

    for epoch in range(1, MAX_EPOCHS + 1):
        model.train()
        model.set_graph_mode("original")
        backbone_trainable = epoch > CFG.freeze_backbone_epochs
        model.set_backbone_trainable(backbone_trainable)
        optimizer.zero_grad(set_to_none=True)
        epoch_losses = []
        progress = tqdm(train_loader, desc=f"{run_name} seed={seed} epoch={epoch}")
        for step, batch in enumerate(progress, start=1):
            labels = batch["word_labels"].to(DEVICE)
            mask = batch["word_mask"].to(DEVICE)
            with torch.amp.autocast(device_type="cuda", enabled=CFG.use_amp):
                emissions = model(batch)
                loss = model.loss(emissions, labels, mask, class_weights)
                scaled_loss = loss / CFG.grad_accum_steps
            scaler.scale(scaled_loss).backward()
            if step % CFG.grad_accum_steps == 0 or step == len(train_loader):
                scaler.unscale_(optimizer)
                nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scale_before = scaler.get_scale()
                scaler.step(optimizer)
                scaler.update()
                if scaler.get_scale() >= scale_before:
                    scheduler.step()
                optimizer.zero_grad(set_to_none=True)
            epoch_losses.append(loss.item())
            progress.set_postfix(loss=f"{np.mean(epoch_losses[-20:]):.4f}")

        model.set_graph_mode("original")
        dev_metrics, _, _, _ = evaluate(model, dev_loader)
        epoch_graph_off_metrics = {}
        if CFG.track_epoch_graph_off:
            model.set_graph_mode("graph_off")
            graph_off_metrics, _, _, _ = evaluate(model, dev_loader)
            epoch_graph_off_metrics = {
                f"dev_epoch_graph_off_{key}": value
                for key, value in graph_off_metrics.items()
            }
            model.set_graph_mode("original")
        row = {
            "epoch": epoch,
            "backbone_trainable": backbone_trainable,
            "train_loss": float(np.mean(epoch_losses)),
            **{f"dev_{key}": value for key, value in dev_metrics.items()},
            **epoch_graph_off_metrics,
        }
        history.append(row)
        print(row)

        current_f1 = dev_metrics["entity_macro_f1"]
        if current_f1 > best_f1 + CFG.min_delta:
            best_f1, best_epoch, stale_epochs = current_f1, epoch, 0
            torch.save(model.state_dict(), checkpoint_path)
        else:
            stale_epochs += 1
            if stale_epochs >= patience:
                print(f"Early stopping at epoch {epoch}.")
                break

    state = torch.load(checkpoint_path, map_location="cpu", weights_only=True)
    model.load_state_dict(state, strict=True)
    model.to(DEVICE).eval()
    pd.DataFrame(history).to_csv(
        ARTIFACT_DIR / f"{run_name}_seed{seed}_history.csv", index=False
    )
    return model, checkpoint_path, history, best_epoch

                    label  train_words    weight
0                       O           31  1.000000
1               S-MENU_NM         5994  0.270638
2              S-MENU_CNT         2126  0.306496
3              S-MENU_NUM           94  3.000000
4        S-MENU_UNITPRICE          629  0.578035
5            S-MENU_PRICE         2236  0.302234
6   S-MENU_DISCOUNT_PRICE          355  0.903049
7              S-SUBTOTAL         1187  0.388415
8              S-DISCOUNT          164  1.783996
9                   S-TAX         1022  0.421619
10              S-SERVICE          274  1.125934
11                S-TOTAL         1700  0.330245
12                 S-CASH         1112  0.402165
13               S-CHANGE         1044  0.416525
14         S-CARD_PAYMENT          326  0.970016
15       S-EMONEY_PAYMENT          115  2.483945
16          S-MENUQTY_CNT          513  0.672469
17         S-MENUTYPE_CNT          105  2.707184
18                S-OTHER          343  0.929373

## 7. Five-Seed Training, Graph Ablations, and Locked Test Evaluation

This section executes five independent training runs, one for each configured seed. For every run, the best checkpoint is selected using development Entity Macro F1 under the original graph topology.

After checkpoint selection, the development split is evaluated under four controlled conditions:

- `original`: the complete symbolic relation graph.
- `shuffled`: node connectivity is permuted within each document while edge attributes are retained.
- `self_loop_only`: inter-word message-passing edges are removed.
- `graph_off`: the graph branch is bypassed and predictions use the separate base classifier.

These ablations distinguish gains caused by meaningful graph topology from gains caused by additional model capacity. Graph evidence is considered supportive when the mean original-minus-graph-off contribution exceeds its sample standard deviation and the original topology outperforms both shuffled and self-loop conditions.

The test split is evaluated only after all five seeds have completed training and all four development ablations. This section also saves per-document predictions, applies the predeclared decision rules, records graph-off behavior across epochs, and computes absolute document-level bootstrap intervals.

In [11]:
BASELINE_DEV_F1 = 0.9256
BASELINE_TEST_MACRO_F1 = 0.9233
COLLAPSE_THRESHOLD = BASELINE_DEV_F1 - 0.015
DEV_GAP_LIMIT = 0.003

PREDECLARED_DECISION_RULES = {
    "rule_A_supportive_hybrid": {
        "graph_contribution": "mean > sample std across five seeds",
        "gap_vs_baseline_dev_reference": (
            "baseline reported dev mean - hybrid five-seed dev mean < 0.003"
        ),
        "test_reference": (
            "five-seed mean test macro F1 > reported baseline mean 0.9233"
        ),
        "conclusion": (
            "Hybrid has supportive five-seed evidence; paired baseline "
            "checkpoints are still required for a strict superiority claim."
        ),
    },
    "rule_B_systematic_base_problem": {
        "collapse": (
            f"at least two seeds have dev graph-off < "
            f"{COLLAPSE_THRESHOLD:.4f}"
        ),
        "graph_contribution": "mean <= sample std",
        "conclusion": (
            "Base-branch collapse is systematic; investigate optimization."
        ),
    },
    "rule_C_hybrid_not_reliable": {
        "gap_vs_baseline_dev_reference": (
            "reported baseline dev mean - hybrid dev mean >= 0.003"
        ),
        "conclusion": (
            "Hybrid is not reliably competitive with the baseline reference."
        ),
    },
}
(ARTIFACT_DIR / "predeclared_decision_rules.json").write_text(
    json.dumps(PREDECLARED_DECISION_RULES, ensure_ascii=False, indent=2),
    encoding="utf-8",
)
print("PREDECLARED DECISION RULES")
display(pd.Series(PREDECLARED_DECISION_RULES))


@torch.no_grad()
def predict_documents(model, loader):
    model.eval()
    if hasattr(model, "set_graph_mode"):
        model.set_graph_mode("original")
    documents = {}
    for batch in tqdm(loader, leave=False, desc="document predictions"):
        labels = batch["word_labels"].to(DEVICE)
        mask = batch["word_mask"].to(DEVICE)
        with torch.amp.autocast(device_type="cuda", enabled=CFG.use_amp):
            emissions = model(batch)
        paths = model.decode(emissions, mask)
        for index, path in enumerate(paths):
            length = int(mask[index].sum())
            documents[batch["ids"][index]] = {
                "gold": labels[index, :length].tolist(),
                "pred": list(path[:length]),
            }
    return documents


def document_bootstrap_absolute(
    documents_by_seed,
    split,
    repetitions,
    bootstrap_seed,
    reference_macro_f1,
):
    document_ids = sorted(next(iter(documents_by_seed.values())))
    for seed, documents in documents_by_seed.items():
        if sorted(documents) != document_ids:
            raise AssertionError(f"Document mismatch for seed {seed}")
        for document_id in document_ids:
            reference_gold = next(iter(documents_by_seed.values()))[
                document_id
            ]["gold"]
            if documents[document_id]["gold"] != reference_gold:
                raise AssertionError(f"Gold mismatch for {document_id}")

    rng = np.random.default_rng(bootstrap_seed)
    sampled_indices = rng.integers(
        0, len(document_ids), size=(repetitions, len(document_ids))
    )
    values_by_seed = {
        int(seed): np.empty(repetitions, dtype=np.float32)
        for seed in documents_by_seed
    }
    for repetition, indices in enumerate(sampled_indices):
        sampled_ids = [document_ids[index] for index in indices]
        gold = [
            label
            for document_id in sampled_ids
            for label in next(iter(documents_by_seed.values()))[
                document_id
            ]["gold"]
        ]
        for seed, documents in documents_by_seed.items():
            prediction = [
                label
                for document_id in sampled_ids
                for label in documents[document_id]["pred"]
            ]
            values_by_seed[int(seed)][repetition] = f1_score(
                gold, prediction, labels=ENTITY_IDS,
                average="macro", zero_division=0,
            )

    rows = []
    for seed, values in values_by_seed.items():
        rows.append({
            "split": split,
            "comparison": f"hybrid_seed_{seed}_absolute",
            "seeds": 1,
            "macro_f1_mean": float(values.mean()),
            "ci95_low": float(np.quantile(values, 0.025)),
            "ci95_high": float(np.quantile(values, 0.975)),
            "reference_macro_f1": reference_macro_f1,
            "delta_vs_reference_mean": float(
                values.mean() - reference_macro_f1
            ),
            "probability_above_reference": float(
                (values > reference_macro_f1).mean()
            ),
            "bootstrap_documents": len(document_ids),
            "bootstrap_repetitions": repetitions,
        })
    stacked = np.stack(list(values_by_seed.values()), axis=0)
    aggregate = stacked.mean(axis=0)
    rows.append({
        "split": split,
        "comparison": "mean_hybrid_across_five_seeds_absolute",
        "seeds": len(values_by_seed),
        "macro_f1_mean": float(aggregate.mean()),
        "ci95_low": float(np.quantile(aggregate, 0.025)),
        "ci95_high": float(np.quantile(aggregate, 0.975)),
        "reference_macro_f1": reference_macro_f1,
        "delta_vs_reference_mean": float(
            aggregate.mean() - reference_macro_f1
        ),
        "probability_above_reference": float(
            (aggregate > reference_macro_f1).mean()
        ),
        "bootstrap_documents": len(document_ids),
        "bootstrap_repetitions": repetitions,
    })
    return pd.DataFrame(rows)


def alpha_tag(alpha):
    return f"a{int(round(float(alpha) * 100)):03d}"


def aux_tag(weight):
    return f"b{int(round(float(weight) * 100)):03d}"


def run_dev_ablation(model, dev_loader):
    mode_metrics = {}
    for graph_mode in ("original", "shuffled", "self_loop_only", "graph_off"):
        model.set_graph_mode(graph_mode)
        metrics, report, golds, preds = evaluate(model, dev_loader)
        mode_metrics[graph_mode] = {
            "metrics": metrics,
            "report": report,
            "golds": golds,
            "preds": preds,
        }
    model.set_graph_mode("original")
    return mode_metrics


def configuration_summary(rows):
    summary = pd.DataFrame([{
        "model": MODEL_NAME,
        "seeds": len(rows),
        "dev_macro_f1_mean": rows["dev_entity_macro_f1"].mean(),
        "dev_macro_f1_std": rows["dev_entity_macro_f1"].std(ddof=1),
        "dev_graph_off_mean": rows["dev_graph_off_entity_macro_f1"].mean(),
        "dev_graph_off_std": rows["dev_graph_off_entity_macro_f1"].std(ddof=1),
        "best_epoch_mean": rows["best_epoch"].mean(),
        "best_epoch_std": rows["best_epoch"].std(ddof=1),
        "graph_contribution_pp_mean": rows["dev_graph_contribution_pp"].mean(),
        "graph_contribution_pp_std": rows["dev_graph_contribution_pp"].std(ddof=1),
        "original_minus_shuffled_pp_mean": rows[
            "dev_original_minus_shuffled_pp"
        ].mean(),
        "original_minus_shuffled_pp_std": rows[
            "dev_original_minus_shuffled_pp"
        ].std(ddof=1),
        "original_minus_self_loop_pp_mean": rows[
            "dev_original_minus_self_loop_pp"
        ].mean(),
        "original_minus_self_loop_pp_std": rows[
            "dev_original_minus_self_loop_pp"
        ].std(ddof=1),
        "wall_minutes_mean": rows["wall_seconds"].mean() / 60,
    }])
    summary["graph_evidence_pass"] = (
        (
            summary["graph_contribution_pp_mean"]
            > summary["graph_contribution_pp_std"]
        )
        & (summary["original_minus_shuffled_pp_mean"] > 0)
        & (summary["original_minus_self_loop_pp_mean"] > 0)
    )
    summary["gap_vs_baseline_dev_pp"] = 100 * (
        summary["dev_macro_f1_mean"] - BASELINE_DEV_F1
    )
    return summary


def run_configuration(
    stage, configuration, graph_alpha, base_aux_weight, patience, seeds
):
    cache_path = ARTIFACT_DIR / f"{configuration}_seed_cache.csv"
    rows = []
    if cache_path.exists():
        cached = pd.read_csv(cache_path)
        for _, cached_row in cached.iterrows():
            checkpoint = Path(cached_row["checkpoint"])
            if int(cached_row["seed"]) in seeds and checkpoint.exists():
                rows.append(cached_row.to_dict())
    run_name = (
        f"{MODEL_NAME}_{configuration}_{alpha_tag(graph_alpha)}_"
        f"{aux_tag(base_aux_weight)}_p{patience}"
    )
    completed = {int(row["seed"]) for row in rows}
    for seed in seeds:
        if seed in completed:
            print("Reusing cached new seed:", seed)
            continue
        print("\n" + "=" * 110)
        print(stage, "|", configuration, "| NEW seed", seed, "| DEV ONLY")
        print("=" * 110)
        set_seed(seed)
        train_loader, dev_loader, _ = make_loaders(seed)
        torch.cuda.reset_peak_memory_stats()
        model = LayoutLMv3SymbolicRelationGATFusionCRF(
            graph_alpha=graph_alpha,
            base_aux_weight=base_aux_weight,
        )
        total_parameters = sum(
            parameter.numel() for parameter in model.parameters()
        )
        trainable_parameters = sum(
            parameter.numel() for parameter in model.parameters()
            if parameter.requires_grad
        )
        started = time.time()
        model, checkpoint_path, history, best_epoch = train_model(
            model, train_loader, dev_loader, run_name, seed, patience
        )
        diagnostic_started = time.time()
        ablation = run_dev_ablation(model, dev_loader)
        diagnostic_seconds = time.time() - diagnostic_started
        original = ablation["original"]["metrics"]
        shuffled = ablation["shuffled"]["metrics"]
        self_loop = ablation["self_loop_only"]["metrics"]
        graph_off = ablation["graph_off"]["metrics"]
        row = {
            "stage": stage,
            "configuration": configuration,
            "model": MODEL_NAME,
            "seed": seed,
            "graph_alpha": float(graph_alpha),
            "base_aux_weight": float(base_aux_weight),
            "patience": int(patience),
            "checkpoint": str(checkpoint_path),
            "source": "trained_from_scratch",
            "initialization": (
                "pretrained_layoutlmv3_plus_random_graph_no_warmstart"
            ),
            "backbone_lr": CFG.backbone_lr,
            "head_lr": CFG.head_lr,
            "graph_lr": CFG.graph_lr,
            "epochs_ran": len(history),
            "best_epoch": int(best_epoch),
            "total_parameters": total_parameters,
            "trainable_parameters": trainable_parameters,
            "wall_seconds": time.time() - started,
            "diagnostic_seconds": diagnostic_seconds,
            "peak_vram_gb": (
                torch.cuda.max_memory_allocated() / (1024 ** 3)
            ),
            "dev_shuffled_entity_macro_f1": shuffled["entity_macro_f1"],
            "dev_self_loop_entity_macro_f1": self_loop["entity_macro_f1"],
            "dev_graph_off_entity_macro_f1": graph_off["entity_macro_f1"],
            "dev_original_minus_shuffled_pp": 100 * (
                original["entity_macro_f1"] - shuffled["entity_macro_f1"]
            ),
            "dev_original_minus_self_loop_pp": 100 * (
                original["entity_macro_f1"] - self_loop["entity_macro_f1"]
            ),
            "dev_graph_contribution_pp": 100 * (
                original["entity_macro_f1"] - graph_off["entity_macro_f1"]
            ),
            **{f"dev_{key}": value for key, value in original.items()},
        }
        rows.append(row)
        pd.DataFrame(rows).sort_values("seed").to_csv(
            cache_path, index=False
        )
        print(pd.Series(row))
        del model, train_loader, dev_loader
        gc.collect()
        torch.cuda.empty_cache()
    frame = pd.DataFrame(rows).sort_values("seed").reset_index(drop=True)
    assert set(frame["seed"].astype(int)) == set(seeds)
    return frame


experiment_started = time.time()
selected_alpha = float(SELECTED_ALPHA)
selected_base_aux = float(SELECTED_BASE_AUX)

dev_sweep_df = run_configuration(
    stage="five_seed_retrain_from_scratch",
    configuration="latest_frozen_a050_b035_five_seed_retrain",
    graph_alpha=selected_alpha,
    base_aux_weight=selected_base_aux,
    patience=PATIENCE,
    seeds=SEEDS,
)
dev_sweep_df = dev_sweep_df.sort_values("seed").reset_index(drop=True)
assert set(dev_sweep_df["seed"].astype(int)) == set(SEEDS)
assert dev_sweep_df["source"].eq("trained_from_scratch").all()
dev_sweep_df.to_csv(
    ARTIFACT_DIR / "dev_ablation_results.csv", index=False
)
configuration_result = configuration_summary(dev_sweep_df)
configuration_result.to_csv(
    ARTIFACT_DIR / "dev_configuration_summary.csv", index=False
)
display(configuration_result)

# Graph-off trajectory diagnosis for every seed, including seed 13.
epoch_diagnostics = []
for _, row in dev_sweep_df.iterrows():
    seed = int(row["seed"])
    history_path = ARTIFACT_DIR / (
        f"{Path(row['checkpoint']).stem}_history.csv"
    )
    history = pd.read_csv(history_path)
    graph_off_column = "dev_epoch_graph_off_entity_macro_f1"
    if graph_off_column not in history:
        raise AssertionError(f"Missing graph-off history for seed {seed}")
    graph_off_change = history[graph_off_column].diff()
    largest_drop_index = graph_off_change.idxmin()
    epoch_diagnostics.append({
        "seed": seed,
        "best_original_epoch": int(row["best_epoch"]),
        "selected_checkpoint_graph_off_f1": float(
            row["dev_graph_off_entity_macro_f1"]
        ),
        "lowest_graph_off_f1": float(history[graph_off_column].min()),
        "lowest_graph_off_epoch": int(
            history.loc[history[graph_off_column].idxmin(), "epoch"]
        ),
        "largest_graph_off_drop": float(
            graph_off_change.loc[largest_drop_index]
        ),
        "largest_graph_off_drop_epoch": int(
            history.loc[largest_drop_index, "epoch"]
        ),
        "sudden_graph_off_drop_ge_1pp": bool(
            graph_off_change.loc[largest_drop_index] <= -0.01
        ),
    })
epoch_diagnostics_df = pd.DataFrame(epoch_diagnostics).sort_values("seed")
epoch_diagnostics_df.to_csv(
    ARTIFACT_DIR / "epoch_graph_off_diagnostics.csv", index=False
)
display(epoch_diagnostics_df)

# Test unlock: only after all five seeds and all dev ablations completed.
selected_rows = []
reports = {}
hybrid_dev_documents = {}
hybrid_test_documents = {}
for seed in SEEDS:
    selected_seed_row = dev_sweep_df[
        dev_sweep_df["seed"].eq(seed)
    ].iloc[0].to_dict()
    checkpoint = Path(selected_seed_row["checkpoint"])
    set_seed(seed)
    _, dev_loader, test_loader = make_loaders(seed)
    model = LayoutLMv3SymbolicRelationGATFusionCRF(
        selected_alpha, selected_base_aux
    ).to(DEVICE)
    state = torch.load(checkpoint, map_location="cpu", weights_only=True)
    model.load_state_dict(state, strict=True)
    model.to(DEVICE).eval()
    model.set_graph_mode("original")
    dev_metrics, dev_report, _, _ = evaluate(model, dev_loader)
    test_metrics, test_report, _, _ = evaluate(model, test_loader)
    hybrid_dev_documents[seed] = predict_documents(model, dev_loader)
    hybrid_test_documents[seed] = predict_documents(model, test_loader)
    selected_seed_row.update({
        **{f"dev_{key}": value for key, value in dev_metrics.items()},
        **{f"test_{key}": value for key, value in test_metrics.items()},
    })
    selected_rows.append(selected_seed_row)
    reports[f"{MODEL_NAME}_seed{seed}"] = {
        "dev": dev_report,
        "test": test_report,
    }
    del model, dev_loader, test_loader
    gc.collect()
    torch.cuda.empty_cache()

results_df = pd.DataFrame(selected_rows).sort_values("seed").reset_index(drop=True)
results_df.to_csv(ARTIFACT_DIR / "experiment_results.csv", index=False)
(ARTIFACT_DIR / "classification_reports.json").write_text(
    json.dumps(reports, ensure_ascii=False, indent=2), encoding="utf-8"
)

bootstrap_dev_df = document_bootstrap_absolute(
    hybrid_dev_documents,
    split="dev_five_seed",
    repetitions=CFG.bootstrap_repetitions,
    bootstrap_seed=20260727,
    reference_macro_f1=BASELINE_DEV_F1,
)
bootstrap_test_df = document_bootstrap_absolute(
    hybrid_test_documents,
    split="test_five_seed",
    repetitions=CFG.bootstrap_repetitions,
    bootstrap_seed=20260728,
    reference_macro_f1=BASELINE_TEST_MACRO_F1,
)
bootstrap_results_df = pd.concat(
    [bootstrap_dev_df, bootstrap_test_df], ignore_index=True
)
bootstrap_results_df.to_csv(
    ARTIFACT_DIR / "bootstrap_hybrid_absolute_results.csv", index=False
)
display(bootstrap_results_df)

(ARTIFACT_DIR / "document_predictions.json").write_text(
    json.dumps(
        {
            "hybrid_dev": hybrid_dev_documents,
            "hybrid_test": hybrid_test_documents,
        },
        ensure_ascii=False,
        default=lambda value: int(value) if isinstance(value, np.integer) else value,
    ),
    encoding="utf-8",
)
total_experiment_minutes = (time.time() - experiment_started) / 60
print("Total five-seed retrain time (min):", total_experiment_minutes)

PREDECLARED DECISION RULES

rule_A_supportive_hybrid          {'graph_contribution': 'mean > sample std acro...
rule_B_systematic_base_problem    {'collapse': 'at least two seeds have dev grap...
rule_C_hybrid_not_reliable        {'gap_vs_baseline_dev_reference': 'reported ba...
dtype: object

==============================================================================================================
five_seed_retrain_from_scratch | latest_frozen_a050_b035_five_seed_retrain | NEW seed 13 | DEV ONLY
==============================================================================================================

model.safetensors:   0%|          | 0.00/501M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/212 [00:00<?, ?it/s]

LayoutLMv3Model LOAD REPORT from: microsoft/layoutlmv3-base
Key                                | Status     |  |
-----------------------------------+------------+--+-
layoutlmv3.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 1, 'backbone_trainable': False, 'train_loss': 1.9058262899518013, 'dev_entity_macro_precision': 0.37978350744536704, 'dev_entity_macro_recall': 0.3427282294563507, 'dev_entity_macro_f1': 0.33373015379930837, 'dev_entity_micro_f1': 0.7031357289997712, 'dev_weighted_f1': 0.6678400133662384, 'dev_loss': 1.1247531127929689, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.5567500998321379, 'dev_graph_residual_norm': 10.572731695148995, 'dev_layer1_attention_entropy': 0.6004620897769928, 'dev_layer1_attention_variance': 0.04376460887491703, 'dev_layer2_attention_entropy': 0.6886633992195129, 'dev_layer2_attention_variance': 0.03326623026281595, 'dev_epoch_graph_off_entity_macro_precision': 0.1301502330483145, 'dev_epoch_graph_off_entity_macro_recall': 0.1373678804297951, 'dev_epoch_graph_off_entity_macro_f1': 0.11017163478626163, 'dev_epoch_graph_off_entity_micro_f1': 0.34470130464637216, 'dev_epoch_graph_off_weighted_f1': 0.30985134996014213, 'dev_epoch_graph_off_loss': 1.907157406806946, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 2, 'backbone_trainable': True, 'train_loss': 0.7391393579542637, 'dev_entity_macro_precision': 0.7228908296801224, 'dev_entity_macro_recall': 0.7462636199742421, 'dev_entity_macro_f1': 0.7257208129824766, 'dev_entity_micro_f1': 0.9384298466468299, 'dev_weighted_f1': 0.9314127206856292, 'dev_loss': 0.23533817384392022, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.8397408859729625, 'dev_graph_residual_norm': 16.072814731999262, 'dev_layer1_attention_entropy': 0.31624176204204557, 'dev_layer1_attention_variance': 0.07535199195146561, 'dev_layer2_attention_entropy': 0.3796940404176712, 'dev_layer2_attention_variance': 0.06816816911101341, 'dev_epoch_graph_off_entity_macro_precision': 0.6423325531600261, 'dev_epoch_graph_off_entity_macro_recall': 0.5402246971777968, 'dev_epoch_graph_off_entity_macro_f1': 0.5547995099202985, 'dev_epoch_graph_off_entity_micro_f1': 0.8995193408102541, 'dev_epoch_graph_off_weighted_f1': 0.8806029024341424, 'dev_epoch_graph_off_loss': 0.3876661178469658, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 3, 'backbone_trainable': True, 'train_loss': 0.25048359800828623, 'dev_entity_macro_precision': 0.8342304455079214, 'dev_entity_macro_recall': 0.8819770840201531, 'dev_entity_macro_f1': 0.849309406580094, 'dev_entity_micro_f1': 0.9631494621194782, 'dev_weighted_f1': 0.9620379588010396, 'dev_loss': 0.1394230162166059, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.7787610691452955, 'dev_graph_residual_norm': 14.875970768906715, 'dev_layer1_attention_entropy': 0.23364952325820923, 'dev_layer1_attention_variance': 0.08560913875699043, 'dev_layer2_attention_entropy': 0.30164609432220457, 'dev_layer2_attention_variance': 0.07637681439518929, 'dev_epoch_graph_off_entity_macro_precision': 0.8130599402923686, 'dev_epoch_graph_off_entity_macro_recall': 0.7986075449405345, 'dev_epoch_graph_off_entity_macro_f1': 0.7902742225143853, 'dev_epoch_graph_off_entity_micro_f1': 0.9571984435797666, 'dev_epoch_graph_off_weighted_f1': 0.951461277249552, 'dev_epoch_graph_off_loss': 0.17628175981342792, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 4, 'backbone_trainable': True, 'train_loss': 0.13777815592824483, 'dev_entity_macro_precision': 0.906208448140239, 'dev_entity_macro_recall': 0.8958507651256922, 'dev_entity_macro_f1': 0.8851043293619799, 'dev_entity_micro_f1': 0.9750514991989013, 'dev_weighted_f1': 0.9724152337054023, 'dev_loss': 0.10670264501590282, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.9496177239343973, 'dev_graph_residual_norm': 18.1007201534177, 'dev_layer1_attention_entropy': 0.20812742859125138, 'dev_layer1_attention_variance': 0.0889849242568016, 'dev_layer2_attention_entropy': 0.24725576490163803, 'dev_layer2_attention_variance': 0.0832540363073349, 'dev_epoch_graph_off_entity_macro_precision': 0.8998646278311205, 'dev_epoch_graph_off_entity_macro_recall': 0.8510970114769444, 'dev_epoch_graph_off_entity_macro_f1': 0.8370957466100694, 'dev_epoch_graph_off_entity_micro_f1': 0.9672693980315862, 'dev_epoch_graph_off_weighted_f1': 0.9627484674930671, 'dev_epoch_graph_off_loss': 0.11247754116076976, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 5, 'backbone_trainable': True, 'train_loss': 0.10125939460180235, 'dev_entity_macro_precision': 0.9165958530135286, 'dev_entity_macro_recall': 0.9058727896051223, 'dev_entity_macro_f1': 0.9048637118429187, 'dev_entity_micro_f1': 0.9814602883955138, 'dev_weighted_f1': 0.9792858340612247, 'dev_loss': 0.09641382410889492, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0041230409190516, 'dev_graph_residual_norm': 19.15247165578718, 'dev_layer1_attention_entropy': 0.19115488409996031, 'dev_layer1_attention_variance': 0.09068460658192634, 'dev_layer2_attention_entropy': 0.23215738147497178, 'dev_layer2_attention_variance': 0.08446209326386452, 'dev_epoch_graph_off_entity_macro_precision': 0.9080091417142714, 'dev_epoch_graph_off_entity_macro_recall': 0.8800883419104788, 'dev_epoch_graph_off_entity_macro_f1': 0.8788811023273928, 'dev_epoch_graph_off_entity_micro_f1': 0.9777981231403067, 'dev_epoch_graph_off_weighted_f1': 0.9750636828466627, 'dev_epoch_graph_off_loss': 0.09716415380593389, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 6, 'backbone_trainable': True, 'train_loss': 0.07875313079130138, 'dev_entity_macro_precision': 0.9065246349764577, 'dev_entity_macro_recall': 0.9071606318313515, 'dev_entity_macro_f1': 0.902037220123819, 'dev_entity_micro_f1': 0.9819180590524147, 'dev_weighted_f1': 0.9799807682761146, 'dev_loss': 0.09633916573657189, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0067377305107044, 'dev_graph_residual_norm': 19.200420718179966, 'dev_layer1_attention_entropy': 0.21263819843530654, 'dev_layer1_attention_variance': 0.08769356787204742, 'dev_layer2_attention_entropy': 0.2348361122608185, 'dev_layer2_attention_variance': 0.08382108837366103, 'dev_epoch_graph_off_entity_macro_precision': 0.9038434642433484, 'dev_epoch_graph_off_entity_macro_recall': 0.9088157031641827, 'dev_epoch_graph_off_entity_macro_f1': 0.8972287191401662, 'dev_epoch_graph_off_entity_micro_f1': 0.9810025177386129, 'dev_epoch_graph_off_weighted_f1': 0.97879880667625, 'dev_epoch_graph_off_loss': 0.09289952693739906, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 7, 'backbone_trainable': True, 'train_loss': 0.05016917403845582, 'dev_entity_macro_precision': 0.9146067613723896, 'dev_entity_macro_recall': 0.9105696992511118, 'dev_entity_macro_f1': 0.9085009137207984, 'dev_entity_micro_f1': 0.9796292057679102, 'dev_weighted_f1': 0.9780755618114795, 'dev_loss': 0.11576559768524021, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0932811792284343, 'dev_graph_residual_norm': 20.814249637251258, 'dev_layer1_attention_entropy': 0.20674864798784257, 'dev_layer1_attention_variance': 0.08817754298448563, 'dev_layer2_attention_entropy': 0.20920791789889337, 'dev_layer2_attention_variance': 0.08729496121406555, 'dev_epoch_graph_off_entity_macro_precision': 0.8975246210443615, 'dev_epoch_graph_off_entity_macro_recall': 0.9027171557735267, 'dev_epoch_graph_off_entity_macro_f1': 0.8927196078204955, 'dev_epoch_graph_off_entity_micro_f1': 0.9768825818265049, 'dev_epoch_graph_off_weighted_f1': 0.9747164965670385, 'dev_epoch_graph_off_loss': 0.1041373210772872, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 8, 'backbone_trainable': True, 'train_loss': 0.049392033324111254, 'dev_entity_macro_precision': 0.8835561788460141, 'dev_entity_macro_recall': 0.9104936683167989, 'dev_entity_macro_f1': 0.8893166416936451, 'dev_entity_micro_f1': 0.9791714351110093, 'dev_weighted_f1': 0.977459850512721, 'dev_loss': 0.11297662993369158, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0818060567194676, 'dev_graph_residual_norm': 20.543908945486727, 'dev_layer1_attention_entropy': 0.2177300450205803, 'dev_layer1_attention_variance': 0.08593983367085457, 'dev_layer2_attention_entropy': 0.1813736654818058, 'dev_layer2_attention_variance': 0.09026803985238076, 'dev_epoch_graph_off_entity_macro_precision': 0.8897215149866553, 'dev_epoch_graph_off_entity_macro_recall': 0.9096087369774111, 'dev_epoch_graph_off_entity_macro_f1': 0.8921214633525404, 'dev_epoch_graph_off_entity_micro_f1': 0.9782558937972076, 'dev_epoch_graph_off_weighted_f1': 0.9765172896421956, 'dev_epoch_graph_off_loss': 0.10453826162498445, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 9, 'backbone_trainable': True, 'train_loss': 0.04098191768585821, 'dev_entity_macro_precision': 0.9023026212047793, 'dev_entity_macro_recall': 0.9087550369128871, 'dev_entity_macro_f1': 0.901149015909701, 'dev_entity_micro_f1': 0.9810025177386129, 'dev_weighted_f1': 0.9793413888571961, 'dev_loss': 0.10958278374921065, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.061977755616418, 'dev_graph_residual_norm': 20.19007066620236, 'dev_layer1_attention_entropy': 0.21600257426500322, 'dev_layer1_attention_variance': 0.08619519114494324, 'dev_layer2_attention_entropy': 0.19488188207149507, 'dev_layer2_attention_variance': 0.08846899285912514, 'dev_epoch_graph_off_entity_macro_precision': 0.8946138223775131, 'dev_epoch_graph_off_entity_macro_recall': 0.8971166775954088, 'dev_epoch_graph_off_entity_macro_f1': 0.8909748309465149, 'dev_epoch_graph_off_entity_micro_f1': 0.9773403524834058, 'dev_epoch_graph_off_weighted_f1': 0.9755207079394062, 'dev_epoch_graph_off_loss': 0.10173639362677932, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 10, 'backbone_trainable': True, 'train_loss': 0.03516521853853192, 'dev_entity_macro_precision': 0.9085411356018542, 'dev_entity_macro_recall': 0.935440784418124, 'dev_entity_macro_f1': 0.918788090289763, 'dev_entity_micro_f1': 0.9823758297093156, 'dev_weighted_f1': 0.9811034941385046, 'dev_loss': 0.10718518806737848, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1571170936125985, 'dev_graph_residual_norm': 22.00222129158655, 'dev_layer1_attention_entropy': 0.21962049961090088, 'dev_layer1_attention_variance': 0.08571751311421394, 'dev_layer2_attention_entropy': 0.21080796271562577, 'dev_layer2_attention_variance': 0.08697814837098122, 'dev_epoch_graph_off_entity_macro_precision': 0.9096797847877514, 'dev_epoch_graph_off_entity_macro_recall': 0.9186685308764186, 'dev_epoch_graph_off_entity_macro_f1': 0.9102740175734056, 'dev_epoch_graph_off_entity_micro_f1': 0.980544747081712, 'dev_epoch_graph_off_weighted_f1': 0.9790846541811098, 'dev_epoch_graph_off_loss': 0.09660896918328944, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 11, 'backbone_trainable': True, 'train_loss': 0.02437130889215041, 'dev_entity_macro_precision': 0.8941429734248223, 'dev_entity_macro_recall': 0.9169594374606205, 'dev_entity_macro_f1': 0.9006413645911899, 'dev_entity_micro_f1': 0.9819180590524147, 'dev_weighted_f1': 0.9806935344203939, 'dev_loss': 0.1101602754931082, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1349038700275438, 'dev_graph_residual_norm': 21.546236601861814, 'dev_layer1_attention_entropy': 0.19814688444137574, 'dev_layer1_attention_variance': 0.08869883134961128, 'dev_layer2_attention_entropy': 0.21546609714627266, 'dev_layer2_attention_variance': 0.08662193715572357, 'dev_epoch_graph_off_entity_macro_precision': 0.8981530526068493, 'dev_epoch_graph_off_entity_macro_recall': 0.9204918641672803, 'dev_epoch_graph_off_entity_macro_f1': 0.9035053664740439, 'dev_epoch_graph_off_entity_micro_f1': 0.980544747081712, 'dev_epoch_graph_off_weighted_f1': 0.9790726967870634, 'dev_epoch_graph_off_loss': 0.09861027997627389, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 12, 'backbone_trainable': True, 'train_loss': 0.01626804627034289, 'dev_entity_macro_precision': 0.8952932573881216, 'dev_entity_macro_recall': 0.9091741120234901, 'dev_entity_macro_f1': 0.897298531781359, 'dev_entity_micro_f1': 0.980544747081712, 'dev_weighted_f1': 0.978971974026813, 'dev_loss': 0.118445259706059, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1491471821990917, 'dev_graph_residual_norm': 21.843424414017825, 'dev_layer1_attention_entropy': 0.20473081558942796, 'dev_layer1_attention_variance': 0.08800444677472115, 'dev_layer2_attention_entropy': 0.22073995143175126, 'dev_layer2_attention_variance': 0.08592988327145576, 'dev_epoch_graph_off_entity_macro_precision': 0.898114251597693, 'dev_epoch_graph_off_entity_macro_recall': 0.9082103570697474, 'dev_epoch_graph_off_entity_macro_f1': 0.8991188632869892, 'dev_epoch_graph_off_entity_micro_f1': 0.9800869764248111, 'dev_epoch_graph_off_weighted_f1': 0.9784855025757894, 'dev_epoch_graph_off_loss': 0.10672818904509768, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 13, 'backbone_trainable': True, 'train_loss': 0.015301457258647132, 'dev_entity_macro_precision': 0.8944000156216452, 'dev_entity_macro_recall': 0.9110803431828332, 'dev_entity_macro_f1': 0.8984945906291002, 'dev_entity_micro_f1': 0.9810025177386129, 'dev_weighted_f1': 0.9794497982525696, 'dev_loss': 0.1195238804660039, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1719745122325644, 'dev_graph_residual_norm': 22.250316232470123, 'dev_layer1_attention_entropy': 0.20137605011463167, 'dev_layer1_attention_variance': 0.08838549345731735, 'dev_layer2_attention_entropy': 0.22392380833625794, 'dev_layer2_attention_variance': 0.08556777715682984, 'dev_epoch_graph_off_entity_macro_precision': 0.8968241837613028, 'dev_epoch_graph_off_entity_macro_recall': 0.9111849642974666, 'dev_epoch_graph_off_entity_macro_f1': 0.8998109525346827, 'dev_epoch_graph_off_entity_micro_f1': 0.9810025177386129, 'dev_epoch_graph_off_weighted_f1': 0.9793961871132388, 'dev_epoch_graph_off_loss': 0.1062837725999998, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 14, 'backbone_trainable': True, 'train_loss': 0.013199803700663324, 'dev_entity_macro_precision': 0.9112264048247981, 'dev_entity_macro_recall': 0.9234164034347487, 'dev_entity_macro_f1': 0.9133875641003163, 'dev_entity_micro_f1': 0.9823758297093156, 'dev_weighted_f1': 0.9810081419471217, 'dev_loss': 0.12003073019412114, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1726816962147724, 'dev_graph_residual_norm': 22.260647312174775, 'dev_layer1_attention_entropy': 0.20273749113082887, 'dev_layer1_attention_variance': 0.08817310109734536, 'dev_layer2_attention_entropy': 0.2251010686159134, 'dev_layer2_attention_variance': 0.08545397222042084, 'dev_epoch_graph_off_entity_macro_precision': 0.8984435794802883, 'dev_epoch_graph_off_entity_macro_recall': 0.908542897965202, 'dev_epoch_graph_off_entity_macro_f1': 0.8990078231612196, 'dev_epoch_graph_off_entity_micro_f1': 0.9796292057679102, 'dev_epoch_graph_off_weighted_f1': 0.9779374389726114, 'dev_epoch_graph_off_loss': 0.10533470317604951, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

stage                                                 five_seed_retrain_from_scratch
configuration                              latest_frozen_a050_b035_five_seed_retrain
model                              layoutlmv3_split_head_symbolic_rel_gatv2_fusio...
seed                                                                              13
graph_alpha                                                                      0.5
base_aux_weight                                                                 0.35
patience                                                                           6
checkpoint                         /kaggle/working/receipt_kie_five_seed_retrain_...
source                                                          trained_from_scratch
initialization                     pretrained_layoutlmv3_plus_random_graph_no_war...
backbone_lr                                                                  0.00001
head_lr                                                                       0.0001
graph_lr                                                                      0.0002
epochs_ran                                                                        14
best_epoch                                                                        10
total_parameters                                                           132271357
trainable_parameters                                                       132271357
wall_seconds                                                             2166.695104
diagnostic_seconds                                                         31.953786
peak_vram_gb                                                                4.396807
dev_shuffled_entity_macro_f1                                                0.900478
dev_self_loop_entity_macro_f1                                               0.916301
dev_graph_off_entity_macro_f1                                               0.910274
dev_original_minus_shuffled_pp                                              1.830989
dev_original_minus_self_loop_pp                                             0.248675
dev_graph_contribution_pp                                                   0.851407
dev_entity_macro_precision                                                  0.908541
dev_entity_macro_recall                                                     0.935441
dev_entity_macro_f1                                                         0.918788
dev_entity_micro_f1                                                         0.982376
dev_weighted_f1                                                             0.981103
dev_loss                                                                    0.107186
dev_graph_alpha                                                                  0.5
dev_graph_residual_base_ratio                                               1.157117
dev_graph_residual_norm                                                    22.002223
dev_layer1_attention_entropy                                                0.219621
dev_layer1_attention_variance                                               0.085718
dev_layer2_attention_entropy                                                0.210808
dev_layer2_attention_variance                                               0.086978
dtype: object

==============================================================================================================
five_seed_retrain_from_scratch | latest_frozen_a050_b035_five_seed_retrain | NEW seed 42 | DEV ONLY
==============================================================================================================

Loading weights:   0%|          | 0/212 [00:00<?, ?it/s]

LayoutLMv3Model LOAD REPORT from: microsoft/layoutlmv3-base
Key                                | Status     |  |
-----------------------------------+------------+--+-
layoutlmv3.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 1, 'backbone_trainable': False, 'train_loss': 1.9418905894458294, 'dev_entity_macro_precision': 0.3848874659163672, 'dev_entity_macro_recall': 0.34628274766441053, 'dev_entity_macro_f1': 0.3349297115124092, 'dev_entity_micro_f1': 0.7017624170290684, 'dev_weighted_f1': 0.6759272608921654, 'dev_loss': 1.1232058906555176, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.5085105220886555, 'dev_graph_residual_norm': 9.656658015552182, 'dev_layer1_attention_entropy': 0.5757624506950378, 'dev_layer1_attention_variance': 0.04591407582163811, 'dev_layer2_attention_entropy': 0.6958499026298522, 'dev_layer2_attention_variance': 0.03200881563127041, 'dev_epoch_graph_off_entity_macro_precision': 0.11627145406002946, 'dev_epoch_graph_off_entity_macro_recall': 0.10628260822459379, 'dev_epoch_graph_off_entity_macro_f1': 0.0928722165963211, 'dev_epoch_graph_off_entity_micro_f1': 0.4097047379262989, 'dev_epoch_graph_off_weighted_f1': 0.2943971294157617, 'dev_epoch_graph_off_loss': 1.7958208870887757, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 2, 'backbone_trainable': True, 'train_loss': 0.7217904557101429, 'dev_entity_macro_precision': 0.777185987316463, 'dev_entity_macro_recall': 0.6932063549397136, 'dev_entity_macro_f1': 0.6977311450417807, 'dev_entity_micro_f1': 0.9315632867933166, 'dev_weighted_f1': 0.9268313778857732, 'dev_loss': 0.2740557191520929, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.8732628022398593, 'dev_graph_residual_norm': 16.763539306417258, 'dev_layer1_attention_entropy': 0.3309686541557312, 'dev_layer1_attention_variance': 0.07412391811609269, 'dev_layer2_attention_entropy': 0.40736086130142213, 'dev_layer2_attention_variance': 0.0643031158298254, 'dev_epoch_graph_off_entity_macro_precision': 0.6256630967276268, 'dev_epoch_graph_off_entity_macro_recall': 0.5270926771012917, 'dev_epoch_graph_off_entity_macro_f1': 0.5320237462380517, 'dev_epoch_graph_off_entity_micro_f1': 0.895857175555047, 'dev_epoch_graph_off_weighted_f1': 0.8738681151505494, 'dev_epoch_graph_off_loss': 0.412498824596405, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 3, 'backbone_trainable': True, 'train_loss': 0.2690917198639363, 'dev_entity_macro_precision': 0.8522194112527038, 'dev_entity_macro_recall': 0.8813708476589067, 'dev_entity_macro_f1': 0.8573356785948116, 'dev_entity_micro_f1': 0.9658960860608835, 'dev_weighted_f1': 0.9645055775693177, 'dev_loss': 0.12759773931466042, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.8692819266118649, 'dev_graph_residual_norm': 16.595299807144542, 'dev_layer1_attention_entropy': 0.24762538611888885, 'dev_layer1_attention_variance': 0.08462256416678429, 'dev_layer2_attention_entropy': 0.2926543256640434, 'dev_layer2_attention_variance': 0.07718775033950806, 'dev_epoch_graph_off_entity_macro_precision': 0.8232067546863071, 'dev_epoch_graph_off_entity_macro_recall': 0.795699881253563, 'dev_epoch_graph_off_entity_macro_f1': 0.7830481977646346, 'dev_epoch_graph_off_entity_micro_f1': 0.9590295262073701, 'dev_epoch_graph_off_weighted_f1': 0.9537716794171742, 'dev_epoch_graph_off_loss': 0.16526850759983064, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 4, 'backbone_trainable': True, 'train_loss': 0.14790760400472208, 'dev_entity_macro_precision': 0.9132912167698062, 'dev_entity_macro_recall': 0.9025295912705269, 'dev_entity_macro_f1': 0.8948863204724626, 'dev_entity_micro_f1': 0.9768825818265049, 'dev_weighted_f1': 0.9745005237320572, 'dev_loss': 0.11520861808210611, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.9654713112705272, 'dev_graph_residual_norm': 18.39449027603303, 'dev_layer1_attention_entropy': 0.20079498142004013, 'dev_layer1_attention_variance': 0.09030849218368531, 'dev_layer2_attention_entropy': 0.20957779467105866, 'dev_layer2_attention_variance': 0.08816754579544067, 'dev_epoch_graph_off_entity_macro_precision': 0.8909115107154604, 'dev_epoch_graph_off_entity_macro_recall': 0.8914061585257529, 'dev_epoch_graph_off_entity_macro_f1': 0.8829525853187503, 'dev_epoch_graph_off_entity_micro_f1': 0.9691004806591897, 'dev_epoch_graph_off_weighted_f1': 0.9668147232895862, 'dev_epoch_graph_off_loss': 0.12295272204559296, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 5, 'backbone_trainable': True, 'train_loss': 0.09699868028284982, 'dev_entity_macro_precision': 0.8844319205601039, 'dev_entity_macro_recall': 0.9076249518079256, 'dev_entity_macro_f1': 0.8869957598120389, 'dev_entity_micro_f1': 0.9750514991989013, 'dev_weighted_f1': 0.9737152242682297, 'dev_loss': 0.11214259566622786, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.9944153641407311, 'dev_graph_residual_norm': 18.865041664730814, 'dev_layer1_attention_entropy': 0.20855648785829545, 'dev_layer1_attention_variance': 0.0887408997118473, 'dev_layer2_attention_entropy': 0.2225635513663292, 'dev_layer2_attention_variance': 0.08590827941894531, 'dev_epoch_graph_off_entity_macro_precision': 0.9179393928437586, 'dev_epoch_graph_off_entity_macro_recall': 0.916601090423847, 'dev_epoch_graph_off_entity_macro_f1': 0.9035704067554343, 'dev_epoch_graph_off_entity_micro_f1': 0.9759670405127031, 'dev_epoch_graph_off_weighted_f1': 0.973928726489647, 'dev_epoch_graph_off_loss': 0.10549512170953676, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 6, 'backbone_trainable': True, 'train_loss': 0.07231831622280879, 'dev_entity_macro_precision': 0.9236731396292382, 'dev_entity_macro_recall': 0.9212155314568423, 'dev_entity_macro_f1': 0.9104593626915418, 'dev_entity_micro_f1': 0.980544747081712, 'dev_weighted_f1': 0.9787908835045166, 'dev_loss': 0.12633629992837087, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0857483301528865, 'dev_graph_residual_norm': 20.550396499563988, 'dev_layer1_attention_entropy': 0.1835007095336914, 'dev_layer1_attention_variance': 0.09203173831105232, 'dev_layer2_attention_entropy': 0.19913788616657258, 'dev_layer2_attention_variance': 0.08871496051549911, 'dev_epoch_graph_off_entity_macro_precision': 0.9071627913572772, 'dev_epoch_graph_off_entity_macro_recall': 0.9127738517848171, 'dev_epoch_graph_off_entity_macro_f1': 0.8948954401124768, 'dev_epoch_graph_off_entity_micro_f1': 0.9768825818265049, 'dev_epoch_graph_off_weighted_f1': 0.9749164587968877, 'dev_epoch_graph_off_loss': 0.11047055759467185, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 7, 'backbone_trainable': True, 'train_loss': 0.055138854658580386, 'dev_entity_macro_precision': 0.9229320723184996, 'dev_entity_macro_recall': 0.9279915226903059, 'dev_entity_macro_f1': 0.9152089295692668, 'dev_entity_micro_f1': 0.9823758297093156, 'dev_weighted_f1': 0.9806109252239186, 'dev_loss': 0.09772860708530061, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0167519917925045, 'dev_graph_residual_norm': 19.266682393596682, 'dev_layer1_attention_entropy': 0.20595156103372575, 'dev_layer1_attention_variance': 0.08811527013778686, 'dev_layer2_attention_entropy': 0.18409356832504273, 'dev_layer2_attention_variance': 0.09064357399940491, 'dev_epoch_graph_off_entity_macro_precision': 0.9145380449647971, 'dev_epoch_graph_off_entity_macro_recall': 0.9290378496681682, 'dev_epoch_graph_off_entity_macro_f1': 0.9130438928122153, 'dev_epoch_graph_off_entity_micro_f1': 0.9800869764248111, 'dev_epoch_graph_off_weighted_f1': 0.97851794600936, 'dev_epoch_graph_off_loss': 0.09062077576294542, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 8, 'backbone_trainable': True, 'train_loss': 0.039501784773456165, 'dev_entity_macro_precision': 0.9302809954249296, 'dev_entity_macro_recall': 0.9317421709328801, 'dev_entity_macro_f1': 0.9260273795125814, 'dev_entity_micro_f1': 0.9846646829938202, 'dev_weighted_f1': 0.9827829088652822, 'dev_loss': 0.10462090373155661, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0278242266653008, 'dev_graph_residual_norm': 19.453022809390724, 'dev_layer1_attention_entropy': 0.2040930989384651, 'dev_layer1_attention_variance': 0.0882057374715805, 'dev_layer2_attention_entropy': 0.19859340995550157, 'dev_layer2_attention_variance': 0.08869946360588074, 'dev_epoch_graph_off_entity_macro_precision': 0.9193053634655054, 'dev_epoch_graph_off_entity_macro_recall': 0.9269428450502998, 'dev_epoch_graph_off_entity_macro_f1': 0.9152743867999581, 'dev_epoch_graph_off_entity_micro_f1': 0.9814602883955138, 'dev_epoch_graph_off_weighted_f1': 0.979566635185599, 'dev_epoch_graph_off_loss': 0.08941460403380916, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 9, 'backbone_trainable': True, 'train_loss': 0.029885699333099182, 'dev_entity_macro_precision': 0.92529435201349, 'dev_entity_macro_recall': 0.9295405243952464, 'dev_entity_macro_f1': 0.9215273147054042, 'dev_entity_micro_f1': 0.9837491416800183, 'dev_weighted_f1': 0.9818424454166393, 'dev_loss': 0.112815388670424, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.184322180142756, 'dev_graph_residual_norm': 22.437376603443255, 'dev_layer1_attention_entropy': 0.18318484842777252, 'dev_layer1_attention_variance': 0.09059859037399293, 'dev_layer2_attention_entropy': 0.189716112613678, 'dev_layer2_attention_variance': 0.08954747810959816, 'dev_epoch_graph_off_entity_macro_precision': 0.9320241031742698, 'dev_epoch_graph_off_entity_macro_recall': 0.9347978400682599, 'dev_epoch_graph_off_entity_macro_f1': 0.9286832894501015, 'dev_epoch_graph_off_entity_micro_f1': 0.9828336003662165, 'dev_epoch_graph_off_weighted_f1': 0.9810354050019221, 'dev_epoch_graph_off_loss': 0.09176910692069214, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 10, 'backbone_trainable': True, 'train_loss': 0.03837324061154504, 'dev_entity_macro_precision': 0.9094185522014734, 'dev_entity_macro_recall': 0.9244191944001989, 'dev_entity_macro_f1': 0.9103439961910507, 'dev_entity_micro_f1': 0.9828336003662165, 'dev_weighted_f1': 0.9815253708703559, 'dev_loss': 0.09949115352355875, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1163242935774207, 'dev_graph_residual_norm': 21.126734615790113, 'dev_layer1_attention_entropy': 0.20584977746009828, 'dev_layer1_attention_variance': 0.08741404309868812, 'dev_layer2_attention_entropy': 0.20581426829099655, 'dev_layer2_attention_variance': 0.08734896689653397, 'dev_epoch_graph_off_entity_macro_precision': 0.9152726167428487, 'dev_epoch_graph_off_entity_macro_recall': 0.9304941001577993, 'dev_epoch_graph_off_entity_macro_f1': 0.9180347378708957, 'dev_epoch_graph_off_entity_micro_f1': 0.9832913710231174, 'dev_epoch_graph_off_weighted_f1': 0.9815494588385327, 'dev_epoch_graph_off_loss': 0.08367689910868649, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 11, 'backbone_trainable': True, 'train_loss': 0.028207016124288203, 'dev_entity_macro_precision': 0.9249325987389609, 'dev_entity_macro_recall': 0.9301653410446309, 'dev_entity_macro_f1': 0.9204579065233216, 'dev_entity_micro_f1': 0.9846646829938202, 'dev_weighted_f1': 0.982701341771032, 'dev_loss': 0.10194802301703021, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0646062251534238, 'dev_graph_residual_norm': 20.145624647637845, 'dev_layer1_attention_entropy': 0.2124483361840248, 'dev_layer1_attention_variance': 0.08614141449332237, 'dev_layer2_attention_entropy': 0.20763843923807143, 'dev_layer2_attention_variance': 0.08697777450084686, 'dev_epoch_graph_off_entity_macro_precision': 0.9296133794176067, 'dev_epoch_graph_off_entity_macro_recall': 0.9302367621641205, 'dev_epoch_graph_off_entity_macro_f1': 0.9233653758693499, 'dev_epoch_graph_off_entity_micro_f1': 0.985122453650721, 'dev_epoch_graph_off_weighted_f1': 0.9831226129937158, 'dev_epoch_graph_off_loss': 0.08567244504985866, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 12, 'backbone_trainable': True, 'train_loss': 0.028281914334729662, 'dev_entity_macro_precision': 0.9255501698843551, 'dev_entity_macro_recall': 0.932487481873017, 'dev_entity_macro_f1': 0.9261934500239268, 'dev_entity_micro_f1': 0.9864957656214237, 'dev_weighted_f1': 0.9847032154796235, 'dev_loss': 0.10712112917390186, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1406470080867608, 'dev_graph_residual_norm': 21.593891614964548, 'dev_layer1_attention_entropy': 0.21646198660135268, 'dev_layer1_attention_variance': 0.08565573468804359, 'dev_layer2_attention_entropy': 0.20572457313537598, 'dev_layer2_attention_variance': 0.08749373137950897, 'dev_epoch_graph_off_entity_macro_precision': 0.9123922659863095, 'dev_epoch_graph_off_entity_macro_recall': 0.9283154779744558, 'dev_epoch_graph_off_entity_macro_f1': 0.9153311425310044, 'dev_epoch_graph_off_entity_micro_f1': 0.9846646829938202, 'dev_epoch_graph_off_weighted_f1': 0.9827913512347272, 'dev_epoch_graph_off_loss': 0.08663112785900012, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 13, 'backbone_trainable': True, 'train_loss': 0.01835361085348268, 'dev_entity_macro_precision': 0.9170258721916452, 'dev_entity_macro_recall': 0.9291458815936748, 'dev_entity_macro_f1': 0.9181402783607359, 'dev_entity_micro_f1': 0.9846646829938202, 'dev_weighted_f1': 0.9827026631742773, 'dev_loss': 0.11003793911077082, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1362104070998638, 'dev_graph_residual_norm': 21.523647967981617, 'dev_layer1_attention_entropy': 0.22198273330926896, 'dev_layer1_attention_variance': 0.0849610611796379, 'dev_layer2_attention_entropy': 0.2043615099787712, 'dev_layer2_attention_variance': 0.08772423952817916, 'dev_epoch_graph_off_entity_macro_precision': 0.9247967523327336, 'dev_epoch_graph_off_entity_macro_recall': 0.9287651359614139, 'dev_epoch_graph_off_entity_macro_f1': 0.9207449601126151, 'dev_epoch_graph_off_entity_micro_f1': 0.9832913710231174, 'dev_epoch_graph_off_weighted_f1': 0.9813640835175748, 'dev_epoch_graph_off_loss': 0.0896488520456478, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 14, 'backbone_trainable': True, 'train_loss': 0.011881252363164094, 'dev_entity_macro_precision': 0.9192367271802782, 'dev_entity_macro_recall': 0.9320083404458289, 'dev_entity_macro_f1': 0.9219717044705055, 'dev_entity_micro_f1': 0.9846646829938202, 'dev_weighted_f1': 0.9828566894458225, 'dev_loss': 0.10884443931281566, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1496518392971087, 'dev_graph_residual_norm': 21.770771497777048, 'dev_layer1_attention_entropy': 0.2196459111571312, 'dev_layer1_attention_variance': 0.08527586519718171, 'dev_layer2_attention_entropy': 0.2032373833656311, 'dev_layer2_attention_variance': 0.08786846533417701, 'dev_epoch_graph_off_entity_macro_precision': 0.9247967523327336, 'dev_epoch_graph_off_entity_macro_recall': 0.9287651359614139, 'dev_epoch_graph_off_entity_macro_f1': 0.9207449601126151, 'dev_epoch_graph_off_entity_micro_f1': 0.9832913710231174, 'dev_epoch_graph_off_weighted_f1': 0.9813640835175748, 'dev_epoch_graph_off_loss': 0.08979380571865477, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

stage                                                 five_seed_retrain_from_scratch
configuration                              latest_frozen_a050_b035_five_seed_retrain
model                              layoutlmv3_split_head_symbolic_rel_gatv2_fusio...
seed                                                                              42
graph_alpha                                                                      0.5
base_aux_weight                                                                 0.35
patience                                                                           6
checkpoint                         /kaggle/working/receipt_kie_five_seed_retrain_...
source                                                          trained_from_scratch
initialization                     pretrained_layoutlmv3_plus_random_graph_no_war...
backbone_lr                                                                  0.00001
head_lr                                                                       0.0001
graph_lr                                                                      0.0002
epochs_ran                                                                        14
best_epoch                                                                        12
total_parameters                                                           132271357
trainable_parameters                                                       132271357
wall_seconds                                                             2153.548209
diagnostic_seconds                                                         29.858356
peak_vram_gb                                                                4.401668
dev_shuffled_entity_macro_f1                                                0.899078
dev_self_loop_entity_macro_f1                                               0.914018
dev_graph_off_entity_macro_f1                                               0.915331
dev_original_minus_shuffled_pp                                              2.711567
dev_original_minus_self_loop_pp                                              1.21758
dev_graph_contribution_pp                                                   1.086231
dev_entity_macro_precision                                                   0.92555
dev_entity_macro_recall                                                     0.932487
dev_entity_macro_f1                                                         0.926193
dev_entity_micro_f1                                                         0.986496
dev_weighted_f1                                                             0.984703
dev_loss                                                                    0.107118
dev_graph_alpha                                                                  0.5
dev_graph_residual_base_ratio                                               1.140646
dev_graph_residual_norm                                                    21.593877
dev_layer1_attention_entropy                                                0.216462
dev_layer1_attention_variance                                               0.085656
dev_layer2_attention_entropy                                                0.205725
dev_layer2_attention_variance                                               0.087494
dtype: object

==============================================================================================================
five_seed_retrain_from_scratch | latest_frozen_a050_b035_five_seed_retrain | NEW seed 2026 | DEV ONLY
==============================================================================================================

Loading weights:   0%|          | 0/212 [00:00<?, ?it/s]

LayoutLMv3Model LOAD REPORT from: microsoft/layoutlmv3-base
Key                                | Status     |  |
-----------------------------------+------------+--+-
layoutlmv3.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 1, 'backbone_trainable': False, 'train_loss': 1.7665705484151841, 'dev_entity_macro_precision': 0.3842094547830983, 'dev_entity_macro_recall': 0.35423269413085917, 'dev_entity_macro_f1': 0.3482522035891744, 'dev_entity_micro_f1': 0.7328908216983291, 'dev_weighted_f1': 0.6958560263746688, 'dev_loss': 1.0449158573150634, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.6114360033327033, 'dev_graph_residual_norm': 11.61122164852774, 'dev_layer1_attention_entropy': 0.7106405127048493, 'dev_layer1_attention_variance': 0.03031085614115, 'dev_layer2_attention_entropy': 0.5981423699855805, 'dev_layer2_attention_variance': 0.043633498772978785, 'dev_epoch_graph_off_entity_macro_precision': 0.17553283114779333, 'dev_epoch_graph_off_entity_macro_recall': 0.13990328931200613, 'dev_epoch_graph_off_entity_macro_f1': 0.11125272989917755, 'dev_epoch_graph_off_entity_micro_f1': 0.47837033646143284, 'dev_epoch_graph_off_weighted_f1': 0.3477899236409053, 'dev_epoch_graph_off_loss': 1.7494960308074952, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 2, 'backbone_trainable': True, 'train_loss': 0.7469628274720163, 'dev_entity_macro_precision': 0.9022707636596701, 'dev_entity_macro_recall': 0.7235763461055966, 'dev_entity_macro_f1': 0.7512817359777403, 'dev_entity_micro_f1': 0.9471274891279469, 'dev_weighted_f1': 0.9390021001671677, 'dev_loss': 0.25487625792622565, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.9054068395250389, 'dev_graph_residual_norm': 17.324162391599774, 'dev_layer1_attention_entropy': 0.4081029897928238, 'dev_layer1_attention_variance': 0.06441755145788193, 'dev_layer2_attention_entropy': 0.27296060413122175, 'dev_layer2_attention_variance': 0.08048936650156975, 'dev_epoch_graph_off_entity_macro_precision': 0.5975608860528199, 'dev_epoch_graph_off_entity_macro_recall': 0.5279464132410111, 'dev_epoch_graph_off_entity_macro_f1': 0.530185866778376, 'dev_epoch_graph_off_entity_micro_f1': 0.8986037994964523, 'dev_epoch_graph_off_weighted_f1': 0.8763254517061687, 'dev_epoch_graph_off_loss': 0.40177067697048185, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 3, 'backbone_trainable': True, 'train_loss': 0.2480033304891549, 'dev_entity_macro_precision': 0.8457500591805575, 'dev_entity_macro_recall': 0.8404345895372635, 'dev_entity_macro_f1': 0.8350491292257695, 'dev_entity_micro_f1': 0.9645227740901808, 'dev_weighted_f1': 0.9603869998002189, 'dev_loss': 0.14749101628083736, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.9705066781419182, 'dev_graph_residual_norm': 18.535588075126515, 'dev_layer1_attention_entropy': 0.34982855975627897, 'dev_layer1_attention_variance': 0.07077393420040608, 'dev_layer2_attention_entropy': 0.24942880213260651, 'dev_layer2_attention_variance': 0.08292859479784966, 'dev_epoch_graph_off_entity_macro_precision': 0.9114506580591161, 'dev_epoch_graph_off_entity_macro_recall': 0.8047947894002032, 'dev_epoch_graph_off_entity_macro_f1': 0.8065567887140134, 'dev_epoch_graph_off_entity_micro_f1': 0.9571984435797666, 'dev_epoch_graph_off_weighted_f1': 0.9507189342349488, 'dev_epoch_graph_off_loss': 0.16058278799057008, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 4, 'backbone_trainable': True, 'train_loss': 0.13662701583234593, 'dev_entity_macro_precision': 0.8479360042878958, 'dev_entity_macro_recall': 0.8906544370640221, 'dev_entity_macro_f1': 0.8550076317010038, 'dev_entity_micro_f1': 0.9695582513160906, 'dev_weighted_f1': 0.9690150871472498, 'dev_loss': 0.11872987699927762, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.9714954883302978, 'dev_graph_residual_norm': 18.519077953677165, 'dev_layer1_attention_entropy': 0.3002608776092529, 'dev_layer1_attention_variance': 0.07696586772799492, 'dev_layer2_attention_entropy': 0.21394082367420197, 'dev_layer2_attention_variance': 0.08672045975923538, 'dev_epoch_graph_off_entity_macro_precision': 0.8494435425346017, 'dev_epoch_graph_off_entity_macro_recall': 0.8798822201416769, 'dev_epoch_graph_off_entity_macro_f1': 0.8446377898302374, 'dev_epoch_graph_off_entity_micro_f1': 0.9622339208056764, 'dev_epoch_graph_off_weighted_f1': 0.9614519483835792, 'dev_epoch_graph_off_loss': 0.11832211573142558, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 5, 'backbone_trainable': True, 'train_loss': 0.11060227924754144, 'dev_entity_macro_precision': 0.9055171972920275, 'dev_entity_macro_recall': 0.909983566958842, 'dev_entity_macro_f1': 0.9009891529477628, 'dev_entity_micro_f1': 0.976424811169604, 'dev_weighted_f1': 0.9743365691275561, 'dev_loss': 0.11386354831047356, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0550226120883992, 'dev_graph_residual_norm': 20.127905940747763, 'dev_layer1_attention_entropy': 0.29308745592832564, 'dev_layer1_attention_variance': 0.0774914987385273, 'dev_layer2_attention_entropy': 0.20157694339752197, 'dev_layer2_attention_variance': 0.08801286771893502, 'dev_epoch_graph_off_entity_macro_precision': 0.8996447658070426, 'dev_epoch_graph_off_entity_macro_recall': 0.90324344288552, 'dev_epoch_graph_off_entity_macro_f1': 0.8904349698062419, 'dev_epoch_graph_off_entity_micro_f1': 0.9745937285420004, 'dev_epoch_graph_off_weighted_f1': 0.9726110839309037, 'dev_epoch_graph_off_loss': 0.10083867262583227, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 6, 'backbone_trainable': True, 'train_loss': 0.07555254821811104, 'dev_entity_macro_precision': 0.8968119081266094, 'dev_entity_macro_recall': 0.9138483677981226, 'dev_entity_macro_f1': 0.8903018659531008, 'dev_entity_micro_f1': 0.980544747081712, 'dev_weighted_f1': 0.9790203256238704, 'dev_loss': 0.09835613255156204, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0463702654937208, 'dev_graph_residual_norm': 19.941005710277224, 'dev_layer1_attention_entropy': 0.29006012916564944, 'dev_layer1_attention_variance': 0.07744605317711831, 'dev_layer2_attention_entropy': 0.1851004469394684, 'dev_layer2_attention_variance': 0.09033752143383027, 'dev_epoch_graph_off_entity_macro_precision': 0.9223800627442833, 'dev_epoch_graph_off_entity_macro_recall': 0.9156172763097952, 'dev_epoch_graph_off_entity_macro_f1': 0.908237676650553, 'dev_epoch_graph_off_entity_micro_f1': 0.9800869764248111, 'dev_epoch_graph_off_weighted_f1': 0.9779922129013848, 'dev_epoch_graph_off_loss': 0.0890728595550172, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 7, 'backbone_trainable': True, 'train_loss': 0.0626981613409589, 'dev_entity_macro_precision': 0.9273144027244944, 'dev_entity_macro_recall': 0.9328875382202781, 'dev_entity_macro_f1': 0.9216973919136784, 'dev_entity_micro_f1': 0.985122453650721, 'dev_weighted_f1': 0.9835349125764078, 'dev_loss': 0.0846577296423493, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.102664039519947, 'dev_graph_residual_norm': 21.010956466688764, 'dev_layer1_attention_entropy': 0.24786370545625686, 'dev_layer1_attention_variance': 0.08276443690061569, 'dev_layer2_attention_entropy': 0.17834791764616967, 'dev_layer2_attention_variance': 0.09084058627486229, 'dev_epoch_graph_off_entity_macro_precision': 0.9219286912594864, 'dev_epoch_graph_off_entity_macro_recall': 0.9402740956008461, 'dev_epoch_graph_off_entity_macro_f1': 0.9252811166879646, 'dev_epoch_graph_off_entity_micro_f1': 0.9846646829938202, 'dev_epoch_graph_off_weighted_f1': 0.9833997679950565, 'dev_epoch_graph_off_loss': 0.06961831993656233, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 8, 'backbone_trainable': True, 'train_loss': 0.04103461054721265, 'dev_entity_macro_precision': 0.9189967552364499, 'dev_entity_macro_recall': 0.9258612046900573, 'dev_entity_macro_f1': 0.91685936647879, 'dev_entity_micro_f1': 0.9837491416800183, 'dev_weighted_f1': 0.9820467013915355, 'dev_loss': 0.1016145647817757, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1601677002627513, 'dev_graph_residual_norm': 22.05845283305874, 'dev_layer1_attention_entropy': 0.2532032033801079, 'dev_layer1_attention_variance': 0.08205301553010941, 'dev_layer2_attention_entropy': 0.17596499338746072, 'dev_layer2_attention_variance': 0.09093556568026542, 'dev_epoch_graph_off_entity_macro_precision': 0.9056652012399433, 'dev_epoch_graph_off_entity_macro_recall': 0.9148604059936906, 'dev_epoch_graph_off_entity_macro_f1': 0.9048286634271194, 'dev_epoch_graph_off_entity_micro_f1': 0.980544747081712, 'dev_epoch_graph_off_weighted_f1': 0.9786359912782753, 'dev_epoch_graph_off_loss': 0.08820055062882602, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 9, 'backbone_trainable': True, 'train_loss': 0.04471318748910562, 'dev_entity_macro_precision': 0.9141930265807567, 'dev_entity_macro_recall': 0.9146087091988875, 'dev_entity_macro_f1': 0.9079134937193073, 'dev_entity_micro_f1': 0.9828336003662165, 'dev_weighted_f1': 0.9807380924780847, 'dev_loss': 0.10603826319507789, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.2030193547683066, 'dev_graph_residual_norm': 22.820850312982472, 'dev_layer1_attention_entropy': 0.2444885841012001, 'dev_layer1_attention_variance': 0.08311578825116157, 'dev_layer2_attention_entropy': 0.17324869975447654, 'dev_layer2_attention_variance': 0.09112256780266761, 'dev_epoch_graph_off_entity_macro_precision': 0.9068307941516353, 'dev_epoch_graph_off_entity_macro_recall': 0.9075683885208602, 'dev_epoch_graph_off_entity_macro_f1': 0.8985161253718661, 'dev_epoch_graph_off_entity_micro_f1': 0.9800869764248111, 'dev_epoch_graph_off_weighted_f1': 0.9778098064484211, 'dev_epoch_graph_off_loss': 0.09146119481418281, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 10, 'backbone_trainable': True, 'train_loss': 0.024668004006671254, 'dev_entity_macro_precision': 0.9255037506404751, 'dev_entity_macro_recall': 0.9293415049821812, 'dev_entity_macro_f1': 0.9220380778986321, 'dev_entity_micro_f1': 0.9855802243076219, 'dev_weighted_f1': 0.983874372060359, 'dev_loss': 0.10200964846764692, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.2094889124205637, 'dev_graph_residual_norm': 22.957061446487412, 'dev_layer1_attention_entropy': 0.2685424375534058, 'dev_layer1_attention_variance': 0.08001996979117393, 'dev_layer2_attention_entropy': 0.17861869260668756, 'dev_layer2_attention_variance': 0.09047523185610772, 'dev_epoch_graph_off_entity_macro_precision': 0.927039703057055, 'dev_epoch_graph_off_entity_macro_recall': 0.9119347625573213, 'dev_epoch_graph_off_entity_macro_f1': 0.9085901795983103, 'dev_epoch_graph_off_entity_micro_f1': 0.9823758297093156, 'dev_epoch_graph_off_weighted_f1': 0.9800389137177893, 'dev_epoch_graph_off_loss': 0.0899356654722942, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 11, 'backbone_trainable': True, 'train_loss': 0.02850688712671399, 'dev_entity_macro_precision': 0.9250837072103797, 'dev_entity_macro_recall': 0.9220731068148582, 'dev_entity_macro_f1': 0.9173030206094354, 'dev_entity_micro_f1': 0.9837491416800183, 'dev_weighted_f1': 0.9818449538961079, 'dev_loss': 0.10535670739394845, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.19560497766161, 'dev_graph_residual_norm': 22.669593999501444, 'dev_layer1_attention_entropy': 0.2741081711649895, 'dev_layer1_attention_variance': 0.07909600749611854, 'dev_layer2_attention_entropy': 0.18190472975373267, 'dev_layer2_attention_variance': 0.09023228198289872, 'dev_epoch_graph_off_entity_macro_precision': 0.9253174881824493, 'dev_epoch_graph_off_entity_macro_recall': 0.9153066381250308, 'dev_epoch_graph_off_entity_macro_f1': 0.9104290491905266, 'dev_epoch_graph_off_entity_micro_f1': 0.9823758297093156, 'dev_epoch_graph_off_weighted_f1': 0.9802872817379847, 'dev_epoch_graph_off_loss': 0.08679285874473862, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 12, 'backbone_trainable': True, 'train_loss': 0.02343182660639286, 'dev_entity_macro_precision': 0.9209234522151386, 'dev_entity_macro_recall': 0.9172623886054472, 'dev_entity_macro_f1': 0.9096541155136423, 'dev_entity_micro_f1': 0.9837491416800183, 'dev_weighted_f1': 0.9815093975904863, 'dev_loss': 0.11502850997145288, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1827409693817141, 'dev_graph_residual_norm': 22.395935337803063, 'dev_layer1_attention_entropy': 0.26408432573080065, 'dev_layer1_attention_variance': 0.08007975950837136, 'dev_layer2_attention_entropy': 0.19297375589609145, 'dev_layer2_attention_variance': 0.08889074921607971, 'dev_epoch_graph_off_entity_macro_precision': 0.9154322281191357, 'dev_epoch_graph_off_entity_macro_recall': 0.9175538734404824, 'dev_epoch_graph_off_entity_macro_f1': 0.9094348515668549, 'dev_epoch_graph_off_entity_micro_f1': 0.9828336003662165, 'dev_epoch_graph_off_weighted_f1': 0.9808446995937296, 'dev_epoch_graph_off_loss': 0.09324389534187504, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 13, 'backbone_trainable': True, 'train_loss': 0.020050461723440095, 'dev_entity_macro_precision': 0.8913570274720405, 'dev_entity_macro_recall': 0.9097266829651662, 'dev_entity_macro_f1': 0.8950855806266667, 'dev_entity_micro_f1': 0.9814602883955138, 'dev_weighted_f1': 0.9792879565153402, 'dev_loss': 0.10704603776073782, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1972141058960444, 'dev_graph_residual_norm': 22.679589357925792, 'dev_layer1_attention_entropy': 0.2604559871554375, 'dev_layer1_attention_variance': 0.08048041999340057, 'dev_layer2_attention_entropy': 0.1925233706831932, 'dev_layer2_attention_variance': 0.0889805130660534, 'dev_epoch_graph_off_entity_macro_precision': 0.9077246520996771, 'dev_epoch_graph_off_entity_macro_recall': 0.9175111383977474, 'dev_epoch_graph_off_entity_macro_f1': 0.9063633961584746, 'dev_epoch_graph_off_entity_micro_f1': 0.9828336003662165, 'dev_epoch_graph_off_weighted_f1': 0.9808672296353667, 'dev_epoch_graph_off_loss': 0.08638287829468026, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 14, 'backbone_trainable': True, 'train_loss': 0.015556811203205144, 'dev_entity_macro_precision': 0.9086622340725492, 'dev_entity_macro_recall': 0.9119489051873886, 'dev_entity_macro_f1': 0.9029371996590189, 'dev_entity_micro_f1': 0.9823758297093156, 'dev_weighted_f1': 0.9800514815952891, 'dev_loss': 0.11161716165486724, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.212031099993077, 'dev_graph_residual_norm': 22.964067310776496, 'dev_layer1_attention_entropy': 0.2609474974870682, 'dev_layer1_attention_variance': 0.08044828236103058, 'dev_layer2_attention_entropy': 0.19216138005256653, 'dev_layer2_attention_variance': 0.08903329879045487, 'dev_epoch_graph_off_entity_macro_precision': 0.9153117618016666, 'dev_epoch_graph_off_entity_macro_recall': 0.9185412647339963, 'dev_epoch_graph_off_entity_macro_f1': 0.9098561165464396, 'dev_epoch_graph_off_entity_micro_f1': 0.9828336003662165, 'dev_epoch_graph_off_weighted_f1': 0.9808558448096782, 'dev_epoch_graph_off_loss': 0.09033708934963215, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

stage                                                 five_seed_retrain_from_scratch
configuration                              latest_frozen_a050_b035_five_seed_retrain
model                              layoutlmv3_split_head_symbolic_rel_gatv2_fusio...
seed                                                                            2026
graph_alpha                                                                      0.5
base_aux_weight                                                                 0.35
patience                                                                           6
checkpoint                         /kaggle/working/receipt_kie_five_seed_retrain_...
source                                                          trained_from_scratch
initialization                     pretrained_layoutlmv3_plus_random_graph_no_war...
backbone_lr                                                                  0.00001
head_lr                                                                       0.0001
graph_lr                                                                      0.0002
epochs_ran                                                                        14
best_epoch                                                                        10
total_parameters                                                           132271357
trainable_parameters                                                       132271357
wall_seconds                                                             2172.409755
diagnostic_seconds                                                         30.868169
peak_vram_gb                                                                4.401668
dev_shuffled_entity_macro_f1                                                0.900852
dev_self_loop_entity_macro_f1                                                0.91391
dev_graph_off_entity_macro_f1                                                0.90859
dev_original_minus_shuffled_pp                                              2.118619
dev_original_minus_self_loop_pp                                             0.812843
dev_graph_contribution_pp                                                    1.34479
dev_entity_macro_precision                                                  0.925504
dev_entity_macro_recall                                                     0.929342
dev_entity_macro_f1                                                         0.922038
dev_entity_micro_f1                                                          0.98558
dev_weighted_f1                                                             0.983874
dev_loss                                                                    0.102009
dev_graph_alpha                                                                  0.5
dev_graph_residual_base_ratio                                               1.209489
dev_graph_residual_norm                                                    22.957065
dev_layer1_attention_entropy                                                0.268542
dev_layer1_attention_variance                                                0.08002
dev_layer2_attention_entropy                                                0.178619
dev_layer2_attention_variance                                               0.090475
dtype: object

==============================================================================================================
five_seed_retrain_from_scratch | latest_frozen_a050_b035_five_seed_retrain | NEW seed 7 | DEV ONLY
==============================================================================================================

Loading weights:   0%|          | 0/212 [00:00<?, ?it/s]

LayoutLMv3Model LOAD REPORT from: microsoft/layoutlmv3-base
Key                                | Status     |  |
-----------------------------------+------------+--+-
layoutlmv3.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 1, 'backbone_trainable': False, 'train_loss': 1.8713671320676804, 'dev_entity_macro_precision': 0.3620407869516921, 'dev_entity_macro_recall': 0.3544662079700658, 'dev_entity_macro_f1': 0.34966954232224157, 'dev_entity_micro_f1': 0.7306019684138246, 'dev_weighted_f1': 0.7049248702869813, 'dev_loss': 1.0847214734554291, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.5684251711382058, 'dev_graph_residual_norm': 10.794442291120161, 'dev_layer1_attention_entropy': 0.6699017703533172, 'dev_layer1_attention_variance': 0.03562148980796337, 'dev_layer2_attention_entropy': 0.5539007544517517, 'dev_layer2_attention_variance': 0.04851346284151077, 'dev_epoch_graph_off_entity_macro_precision': 0.11200715775140718, 'dev_epoch_graph_off_entity_macro_recall': 0.14777992862936343, 'dev_epoch_graph_off_entity_macro_f1': 0.11177628704877342, 'dev_epoch_graph_off_entity_micro_f1': 0.4816973653532292, 'dev_epoch_graph_off_weighted_f1': 0.3491999068851146, 'dev_epoch_graph_off_loss': 1.8574742102622985, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 2, 'backbone_trainable': True, 'train_loss': 0.7141036099009216, 'dev_entity_macro_precision': 0.7534110746485498, 'dev_entity_macro_recall': 0.7354806428548945, 'dev_entity_macro_f1': 0.7280311321644112, 'dev_entity_micro_f1': 0.9420920119020371, 'dev_weighted_f1': 0.9361348527695901, 'dev_loss': 0.2520506367087364, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.8350214296330845, 'dev_graph_residual_norm': 16.102985992850453, 'dev_layer1_attention_entropy': 0.41079374849796296, 'dev_layer1_attention_variance': 0.06467896707355976, 'dev_layer2_attention_entropy': 0.2708808171749115, 'dev_layer2_attention_variance': 0.08140110567212105, 'dev_epoch_graph_off_entity_macro_precision': 0.6324514821033616, 'dev_epoch_graph_off_entity_macro_recall': 0.5476537508359642, 'dev_epoch_graph_off_entity_macro_f1': 0.5591837851976504, 'dev_epoch_graph_off_entity_micro_f1': 0.8976882581826505, 'dev_epoch_graph_off_weighted_f1': 0.8805807190236908, 'dev_epoch_graph_off_loss': 0.3889998518675566, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 3, 'backbone_trainable': True, 'train_loss': 0.27191935109673065, 'dev_entity_macro_precision': 0.8789132221312705, 'dev_entity_macro_recall': 0.8868798943600069, 'dev_entity_macro_f1': 0.874032521513986, 'dev_entity_micro_f1': 0.9727626459143969, 'dev_weighted_f1': 0.9707914212676035, 'dev_loss': 0.13318602400831878, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.8604259073794494, 'dev_graph_residual_norm': 16.51329725986212, 'dev_layer1_attention_entropy': 0.31862819075584414, 'dev_layer1_attention_variance': 0.07511844217777253, 'dev_layer2_attention_entropy': 0.23089512854814528, 'dev_layer2_attention_variance': 0.08442168533802033, 'dev_epoch_graph_off_entity_macro_precision': 0.935655731937294, 'dev_epoch_graph_off_entity_macro_recall': 0.8197244294249043, 'dev_epoch_graph_off_entity_macro_f1': 0.8344376086632378, 'dev_epoch_graph_off_entity_micro_f1': 0.963607232776379, 'dev_epoch_graph_off_weighted_f1': 0.9579299090662221, 'dev_epoch_graph_off_loss': 0.16000350259244442, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 4, 'backbone_trainable': True, 'train_loss': 0.15152482463628986, 'dev_entity_macro_precision': 0.8799542790899978, 'dev_entity_macro_recall': 0.8843087892317204, 'dev_entity_macro_f1': 0.8727680095816678, 'dev_entity_micro_f1': 0.9750514991989013, 'dev_weighted_f1': 0.9724005859346374, 'dev_loss': 0.11614341338863596, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.9781876286073116, 'dev_graph_residual_norm': 18.685926529866016, 'dev_layer1_attention_entropy': 0.29230602651834486, 'dev_layer1_attention_variance': 0.07823403373360634, 'dev_layer2_attention_entropy': 0.20068886548280715, 'dev_layer2_attention_variance': 0.08831157192587852, 'dev_epoch_graph_off_entity_macro_precision': 0.914679432763804, 'dev_epoch_graph_off_entity_macro_recall': 0.8506551324202155, 'dev_epoch_graph_off_entity_macro_f1': 0.8401782162124705, 'dev_epoch_graph_off_entity_micro_f1': 0.9713893339436942, 'dev_epoch_graph_off_weighted_f1': 0.9668177541787225, 'dev_epoch_graph_off_loss': 0.1191688071936369, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 5, 'backbone_trainable': True, 'train_loss': 0.09677501381898765, 'dev_entity_macro_precision': 0.8964238842101447, 'dev_entity_macro_recall': 0.8899122409579208, 'dev_entity_macro_f1': 0.8819783179871221, 'dev_entity_micro_f1': 0.9782558937972076, 'dev_weighted_f1': 0.9760934378523161, 'dev_loss': 0.09983170146122575, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0291464422125358, 'dev_graph_residual_norm': 19.65995609880257, 'dev_layer1_attention_entropy': 0.26232576310634614, 'dev_layer1_attention_variance': 0.08114445716142654, 'dev_layer2_attention_entropy': 0.16870016366243362, 'dev_layer2_attention_variance': 0.0923592908680439, 'dev_epoch_graph_off_entity_macro_precision': 0.9142137131969833, 'dev_epoch_graph_off_entity_macro_recall': 0.866222880189326, 'dev_epoch_graph_off_entity_macro_f1': 0.8585297412350351, 'dev_epoch_graph_off_entity_micro_f1': 0.9745937285420004, 'dev_epoch_graph_off_weighted_f1': 0.9710422061123747, 'dev_epoch_graph_off_loss': 0.09394685562700034, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 6, 'backbone_trainable': True, 'train_loss': 0.0733364135643933, 'dev_entity_macro_precision': 0.9272103181447338, 'dev_entity_macro_recall': 0.939373617522487, 'dev_entity_macro_f1': 0.9236223416754085, 'dev_entity_micro_f1': 0.9860379949645228, 'dev_weighted_f1': 0.9846917793178628, 'dev_loss': 0.07404473662492819, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.9620636766333619, 'dev_graph_residual_norm': 18.362947985761664, 'dev_layer1_attention_entropy': 0.2570454552769661, 'dev_layer1_attention_variance': 0.0809879718720913, 'dev_layer2_attention_entropy': 0.1973222601413727, 'dev_layer2_attention_variance': 0.08809343531727791, 'dev_epoch_graph_off_entity_macro_precision': 0.9191952170266462, 'dev_epoch_graph_off_entity_macro_recall': 0.9321090744499951, 'dev_epoch_graph_off_entity_macro_f1': 0.9187073582476937, 'dev_epoch_graph_off_entity_micro_f1': 0.9832913710231174, 'dev_epoch_graph_off_weighted_f1': 0.9816364221618344, 'dev_epoch_graph_off_loss': 0.06999765642452985, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 7, 'backbone_trainable': True, 'train_loss': 0.060201567740296016, 'dev_entity_macro_precision': 0.9448959673603685, 'dev_entity_macro_recall': 0.9278719325951853, 'dev_entity_macro_f1': 0.9229652672262749, 'dev_entity_micro_f1': 0.9874113069352255, 'dev_weighted_f1': 0.9856239862703698, 'dev_loss': 0.0895021302998066, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0430291156965052, 'dev_graph_residual_norm': 19.942539937541994, 'dev_layer1_attention_entropy': 0.23168759316205978, 'dev_layer1_attention_variance': 0.08422609493136406, 'dev_layer2_attention_entropy': 0.14769286513328553, 'dev_layer2_attention_variance': 0.09460359290242196, 'dev_epoch_graph_off_entity_macro_precision': 0.9234159009378907, 'dev_epoch_graph_off_entity_macro_recall': 0.9032819380445419, 'dev_epoch_graph_off_entity_macro_f1': 0.8917588076710514, 'dev_epoch_graph_off_entity_micro_f1': 0.9814602883955138, 'dev_epoch_graph_off_weighted_f1': 0.9783062246842782, 'dev_epoch_graph_off_loss': 0.08488927537458948, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 8, 'backbone_trainable': True, 'train_loss': 0.04405235953410738, 'dev_entity_macro_precision': 0.9122363531679469, 'dev_entity_macro_recall': 0.9205274657432381, 'dev_entity_macro_f1': 0.9050668855616963, 'dev_entity_micro_f1': 0.9828336003662165, 'dev_weighted_f1': 0.9811688343437592, 'dev_loss': 0.09387187097920105, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0836893192092933, 'dev_graph_residual_norm': 20.689514844219072, 'dev_layer1_attention_entropy': 0.22700151473283767, 'dev_layer1_attention_variance': 0.08494364619255065, 'dev_layer2_attention_entropy': 0.13691332191228867, 'dev_layer2_attention_variance': 0.0958984649181366, 'dev_epoch_graph_off_entity_macro_precision': 0.919709489843775, 'dev_epoch_graph_off_entity_macro_recall': 0.9217296690429174, 'dev_epoch_graph_off_entity_macro_f1': 0.9073876337191457, 'dev_epoch_graph_off_entity_micro_f1': 0.9832913710231174, 'dev_epoch_graph_off_weighted_f1': 0.9814914553899898, 'dev_epoch_graph_off_loss': 0.0823570209054742, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 9, 'backbone_trainable': True, 'train_loss': 0.03064445738622453, 'dev_entity_macro_precision': 0.9370748994895154, 'dev_entity_macro_recall': 0.9235763585295902, 'dev_entity_macro_f1': 0.91850941965449, 'dev_entity_micro_f1': 0.9842069123369191, 'dev_weighted_f1': 0.9819257603758034, 'dev_loss': 0.10447619576298166, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0883636108169217, 'dev_graph_residual_norm': 20.760878888380603, 'dev_layer1_attention_entropy': 0.21410871416330338, 'dev_layer1_attention_variance': 0.08617437034845352, 'dev_layer2_attention_entropy': 0.13365897804498672, 'dev_layer2_attention_variance': 0.0962478706240654, 'dev_epoch_graph_off_entity_macro_precision': 0.9362799572427263, 'dev_epoch_graph_off_entity_macro_recall': 0.9235377129045188, 'dev_epoch_graph_off_entity_macro_f1': 0.917986965148728, 'dev_epoch_graph_off_entity_micro_f1': 0.9837491416800183, 'dev_epoch_graph_off_weighted_f1': 0.981500542486184, 'dev_epoch_graph_off_loss': 0.08818063771177549, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 10, 'backbone_trainable': True, 'train_loss': 0.0279706150675338, 'dev_entity_macro_precision': 0.9285269932912763, 'dev_entity_macro_recall': 0.9252991660365752, 'dev_entity_macro_f1': 0.9162828729729511, 'dev_entity_micro_f1': 0.985122453650721, 'dev_weighted_f1': 0.9830020113007244, 'dev_loss': 0.10850198283966166, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.053295483710794, 'dev_graph_residual_norm': 20.083492785119617, 'dev_layer1_attention_entropy': 0.2280488756299019, 'dev_layer1_attention_variance': 0.0842275232076645, 'dev_layer2_attention_entropy': 0.13506436243653297, 'dev_layer2_attention_variance': 0.09615501329302788, 'dev_epoch_graph_off_entity_macro_precision': 0.9187307628439565, 'dev_epoch_graph_off_entity_macro_recall': 0.918351695690412, 'dev_epoch_graph_off_entity_macro_f1': 0.9068702211914369, 'dev_epoch_graph_off_entity_micro_f1': 0.9832913710231174, 'dev_epoch_graph_off_weighted_f1': 0.9811336583215993, 'dev_epoch_graph_off_loss': 0.09026798660110216, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 11, 'backbone_trainable': True, 'train_loss': 0.02288842159563501, 'dev_entity_macro_precision': 0.9387319196006059, 'dev_entity_macro_recall': 0.9274978708415785, 'dev_entity_macro_f1': 0.9212678001521487, 'dev_entity_micro_f1': 0.9874113069352255, 'dev_weighted_f1': 0.985173453059632, 'dev_loss': 0.0916006382217165, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1331790168120568, 'dev_graph_residual_norm': 21.580232779039555, 'dev_layer1_attention_entropy': 0.21966213762760162, 'dev_layer1_attention_variance': 0.08511803030967713, 'dev_layer2_attention_entropy': 0.13562385722994805, 'dev_layer2_attention_variance': 0.09587951272726059, 'dev_epoch_graph_off_entity_macro_precision': 0.933496532259017, 'dev_epoch_graph_off_entity_macro_recall': 0.926268218219421, 'dev_epoch_graph_off_entity_macro_f1': 0.917751867683097, 'dev_epoch_graph_off_entity_micro_f1': 0.9855802243076219, 'dev_epoch_graph_off_weighted_f1': 0.9833813803805499, 'dev_epoch_graph_off_loss': 0.07952647854224779, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 12, 'backbone_trainable': True, 'train_loss': 0.02378346940247866, 'dev_entity_macro_precision': 0.9348421639744386, 'dev_entity_macro_recall': 0.9298305790950037, 'dev_entity_macro_f1': 0.9245495631416065, 'dev_entity_micro_f1': 0.9860379949645228, 'dev_weighted_f1': 0.983931992969452, 'dev_loss': 0.08734575680020498, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1735125614608484, 'dev_graph_residual_norm': 22.343912904674813, 'dev_layer1_attention_entropy': 0.2292358347773552, 'dev_layer1_attention_variance': 0.08387468725442887, 'dev_layer2_attention_entropy': 0.1312250867486, 'dev_layer2_attention_variance': 0.09639042779803277, 'dev_epoch_graph_off_entity_macro_precision': 0.9387881112768004, 'dev_epoch_graph_off_entity_macro_recall': 0.9266199536738857, 'dev_epoch_graph_off_entity_macro_f1': 0.9209487609909157, 'dev_epoch_graph_off_entity_micro_f1': 0.9864957656214237, 'dev_epoch_graph_off_weighted_f1': 0.9842228794652559, 'dev_epoch_graph_off_loss': 0.07731577869097236, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 13, 'backbone_trainable': True, 'train_loss': 0.015761213915175175, 'dev_entity_macro_precision': 0.924722464349878, 'dev_entity_macro_recall': 0.922875600010777, 'dev_entity_macro_f1': 0.9140747177391686, 'dev_entity_micro_f1': 0.9846646829938202, 'dev_weighted_f1': 0.982682080733547, 'dev_loss': 0.10143633396495716, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.188450198369714, 'dev_graph_residual_norm': 22.640691772907672, 'dev_layer1_attention_entropy': 0.23007909089326858, 'dev_layer1_attention_variance': 0.08365060105919837, 'dev_layer2_attention_entropy': 0.1369332292675972, 'dev_layer2_attention_variance': 0.0955509440600872, 'dev_epoch_graph_off_entity_macro_precision': 0.9239671883815643, 'dev_epoch_graph_off_entity_macro_recall': 0.9228756000107767, 'dev_epoch_graph_off_entity_macro_f1': 0.9126389540556029, 'dev_epoch_graph_off_entity_micro_f1': 0.985122453650721, 'dev_epoch_graph_off_weighted_f1': 0.9828975435683447, 'dev_epoch_graph_off_loss': 0.08482689380878583, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 14, 'backbone_trainable': True, 'train_loss': 0.015192811064407579, 'dev_entity_macro_precision': 0.9417475917091939, 'dev_entity_macro_recall': 0.9253611187048265, 'dev_entity_macro_f1': 0.9230140618175581, 'dev_entity_micro_f1': 0.9860379949645228, 'dev_weighted_f1': 0.9839985365540697, 'dev_loss': 0.10419489706779132, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1872006225003622, 'dev_graph_residual_norm': 22.609380989039806, 'dev_layer1_attention_entropy': 0.23157949417829513, 'dev_layer1_attention_variance': 0.08344826728105545, 'dev_layer2_attention_entropy': 0.1366915547847748, 'dev_layer2_attention_variance': 0.09552970856428146, 'dev_epoch_graph_off_entity_macro_precision': 0.9310088939526816, 'dev_epoch_graph_off_entity_macro_recall': 0.9242500075937152, 'dev_epoch_graph_off_entity_macro_f1': 0.9166488027839436, 'dev_epoch_graph_off_entity_micro_f1': 0.9860379949645228, 'dev_epoch_graph_off_weighted_f1': 0.9837627250223048, 'dev_epoch_graph_off_loss': 0.08584760987316259, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

stage                                                 five_seed_retrain_from_scratch
configuration                              latest_frozen_a050_b035_five_seed_retrain
model                              layoutlmv3_split_head_symbolic_rel_gatv2_fusio...
seed                                                                               7
graph_alpha                                                                      0.5
base_aux_weight                                                                 0.35
patience                                                                           6
checkpoint                         /kaggle/working/receipt_kie_five_seed_retrain_...
source                                                          trained_from_scratch
initialization                     pretrained_layoutlmv3_plus_random_graph_no_war...
backbone_lr                                                                  0.00001
head_lr                                                                       0.0001
graph_lr                                                                      0.0002
epochs_ran                                                                        14
best_epoch                                                                        12
total_parameters                                                           132271357
trainable_parameters                                                       132271357
wall_seconds                                                             2192.742844
diagnostic_seconds                                                          31.06413
peak_vram_gb                                                                4.401669
dev_shuffled_entity_macro_f1                                                0.905846
dev_self_loop_entity_macro_f1                                               0.925349
dev_graph_off_entity_macro_f1                                               0.920949
dev_original_minus_shuffled_pp                                              1.870348
dev_original_minus_self_loop_pp                                              -0.0799
dev_graph_contribution_pp                                                    0.36008
dev_entity_macro_precision                                                  0.934842
dev_entity_macro_recall                                                     0.929831
dev_entity_macro_f1                                                          0.92455
dev_entity_micro_f1                                                         0.986038
dev_weighted_f1                                                             0.983932
dev_loss                                                                    0.087347
dev_graph_alpha                                                                  0.5
dev_graph_residual_base_ratio                                               1.173512
dev_graph_residual_norm                                                    22.343905
dev_layer1_attention_entropy                                                0.229236
dev_layer1_attention_variance                                               0.083875
dev_layer2_attention_entropy                                                0.131225
dev_layer2_attention_variance                                                0.09639
dtype: object

==============================================================================================================
five_seed_retrain_from_scratch | latest_frozen_a050_b035_five_seed_retrain | NEW seed 123 | DEV ONLY
==============================================================================================================

Loading weights:   0%|          | 0/212 [00:00<?, ?it/s]

LayoutLMv3Model LOAD REPORT from: microsoft/layoutlmv3-base
Key                                | Status     |  |
-----------------------------------+------------+--+-
layoutlmv3.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 1, 'backbone_trainable': False, 'train_loss': 1.8859231029450894, 'dev_entity_macro_precision': 0.39473400125198976, 'dev_entity_macro_recall': 0.3351740748885199, 'dev_entity_macro_f1': 0.3115123993614127, 'dev_entity_micro_f1': 0.6944380865186541, 'dev_weighted_f1': 0.6546745154777889, 'dev_loss': 1.1460419178009034, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.5500793265916661, 'dev_graph_residual_norm': 10.446053144589326, 'dev_layer1_attention_entropy': 0.7153284251689911, 'dev_layer1_attention_variance': 0.030106949396431448, 'dev_layer2_attention_entropy': 0.4668814796209335, 'dev_layer2_attention_variance': 0.059028099179267886, 'dev_epoch_graph_off_entity_macro_precision': 0.1545947033125972, 'dev_epoch_graph_off_entity_macro_recall': 0.11173292087205981, 'dev_epoch_graph_off_entity_macro_f1': 0.09239387452759407, 'dev_epoch_graph_off_entity_micro_f1': 0.4174868390936141, 'dev_epoch_graph_off_weighted_f1': 0.2903803312825164, 'dev_epoch_graph_off_loss': 1.8276782298088075, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 2, 'backbone_trainable': True, 'train_loss': 0.7578798579610884, 'dev_entity_macro_precision': 0.7816875501555726, 'dev_entity_macro_recall': 0.7674090320631053, 'dev_entity_macro_f1': 0.7471495740268425, 'dev_entity_micro_f1': 0.9356832227054246, 'dev_weighted_f1': 0.9360207406794767, 'dev_loss': 0.23845511566847563, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.8365764311432823, 'dev_graph_residual_norm': 15.953343928023859, 'dev_layer1_attention_entropy': 0.5401564466953278, 'dev_layer1_attention_variance': 0.048788002356886864, 'dev_layer2_attention_entropy': 0.23607102185487747, 'dev_layer2_attention_variance': 0.08467052772641182, 'dev_epoch_graph_off_entity_macro_precision': 0.6065684768637448, 'dev_epoch_graph_off_entity_macro_recall': 0.5625647318028264, 'dev_epoch_graph_off_entity_macro_f1': 0.5721550600248322, 'dev_epoch_graph_off_entity_micro_f1': 0.9073014419775692, 'dev_epoch_graph_off_weighted_f1': 0.8926597796204767, 'dev_epoch_graph_off_loss': 0.3612057174742222, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 3, 'backbone_trainable': True, 'train_loss': 0.25819077852182093, 'dev_entity_macro_precision': 0.8813876891301706, 'dev_entity_macro_recall': 0.8350048442767392, 'dev_entity_macro_f1': 0.8287145441591677, 'dev_entity_micro_f1': 0.9658960860608835, 'dev_weighted_f1': 0.9625300802205259, 'dev_loss': 0.14301764939911663, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.888600643644301, 'dev_graph_residual_norm': 16.987208611574722, 'dev_layer1_attention_entropy': 0.4326911771297455, 'dev_layer1_attention_variance': 0.06185559891164303, 'dev_layer2_attention_entropy': 0.18055117279291152, 'dev_layer2_attention_variance': 0.09062655985355378, 'dev_epoch_graph_off_entity_macro_precision': 0.8563385562117491, 'dev_epoch_graph_off_entity_macro_recall': 0.8117688393066219, 'dev_epoch_graph_off_entity_macro_f1': 0.8141709535669358, 'dev_epoch_graph_off_entity_micro_f1': 0.9512474250400549, 'dev_epoch_graph_off_weighted_f1': 0.9466677230379235, 'dev_epoch_graph_off_loss': 0.17489473829045893, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 4, 'backbone_trainable': True, 'train_loss': 0.1431217609148007, 'dev_entity_macro_precision': 0.8838878255471232, 'dev_entity_macro_recall': 0.9013436887924053, 'dev_entity_macro_f1': 0.8838577345879878, 'dev_entity_micro_f1': 0.9777981231403067, 'dev_weighted_f1': 0.9759846717532911, 'dev_loss': 0.10020988439675421, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.8868655301770245, 'dev_graph_residual_norm': 16.89551674719808, 'dev_layer1_attention_entropy': 0.3768141108751297, 'dev_layer1_attention_variance': 0.06803478181362152, 'dev_layer2_attention_entropy': 0.17002855092287064, 'dev_layer2_attention_variance': 0.09188249230384826, 'dev_epoch_graph_off_entity_macro_precision': 0.8669608377270711, 'dev_epoch_graph_off_entity_macro_recall': 0.8901301539099801, 'dev_epoch_graph_off_entity_macro_f1': 0.8635067361709076, 'dev_epoch_graph_off_entity_micro_f1': 0.9700160219729915, 'dev_epoch_graph_off_weighted_f1': 0.9682165140829169, 'dev_epoch_graph_off_loss': 0.10726254123728722, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 5, 'backbone_trainable': True, 'train_loss': 0.11537956934247631, 'dev_entity_macro_precision': 0.8762221660830117, 'dev_entity_macro_recall': 0.9159791738863419, 'dev_entity_macro_f1': 0.8832905613070176, 'dev_entity_micro_f1': 0.9759670405127031, 'dev_weighted_f1': 0.9748128726985579, 'dev_loss': 0.09150307737174444, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.907833515956664, 'dev_graph_residual_norm': 17.272167404747183, 'dev_layer1_attention_entropy': 0.34255223512649535, 'dev_layer1_attention_variance': 0.07154047049582005, 'dev_layer2_attention_entropy': 0.17979444801807404, 'dev_layer2_attention_variance': 0.09049376055598259, 'dev_epoch_graph_off_entity_macro_precision': 0.8830025035974055, 'dev_epoch_graph_off_entity_macro_recall': 0.8986561454195192, 'dev_epoch_graph_off_entity_macro_f1': 0.8772902956699631, 'dev_epoch_graph_off_entity_micro_f1': 0.9732204165712978, 'dev_epoch_graph_off_weighted_f1': 0.9710593999437525, 'dev_epoch_graph_off_loss': 0.09518974144477398, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 6, 'backbone_trainable': True, 'train_loss': 0.07089587098074844, 'dev_entity_macro_precision': 0.9164572974242523, 'dev_entity_macro_recall': 0.9194759025349118, 'dev_entity_macro_f1': 0.9060255411489879, 'dev_entity_micro_f1': 0.9814602883955138, 'dev_weighted_f1': 0.9794462149694053, 'dev_loss': 0.09859044682001696, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.9501309431081387, 'dev_graph_residual_norm': 18.034243989405233, 'dev_layer1_attention_entropy': 0.3139878085255623, 'dev_layer1_attention_variance': 0.07463021740317345, 'dev_layer2_attention_entropy': 0.19891041100025178, 'dev_layer2_attention_variance': 0.08755026787519454, 'dev_epoch_graph_off_entity_macro_precision': 0.9082651409328323, 'dev_epoch_graph_off_entity_macro_recall': 0.9136954628882464, 'dev_epoch_graph_off_entity_macro_f1': 0.9009871276289481, 'dev_epoch_graph_off_entity_micro_f1': 0.9787136644541085, 'dev_epoch_graph_off_weighted_f1': 0.9763288859342769, 'dev_epoch_graph_off_loss': 0.09166255169082432, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 7, 'backbone_trainable': True, 'train_loss': 0.06483926201530267, 'dev_entity_macro_precision': 0.9120936836517042, 'dev_entity_macro_recall': 0.9305940931322285, 'dev_entity_macro_f1': 0.917906919192985, 'dev_entity_micro_f1': 0.9832913710231174, 'dev_weighted_f1': 0.9816303002788248, 'dev_loss': 0.10573388288496062, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.914473944505244, 'dev_graph_residual_norm': 17.41658476526761, 'dev_layer1_attention_entropy': 0.3059563198685646, 'dev_layer1_attention_variance': 0.07577244117856026, 'dev_layer2_attention_entropy': 0.18584522902965545, 'dev_layer2_attention_variance': 0.08882501631975175, 'dev_epoch_graph_off_entity_macro_precision': 0.9230185931504225, 'dev_epoch_graph_off_entity_macro_recall': 0.931423978238344, 'dev_epoch_graph_off_entity_macro_f1': 0.922415675734631, 'dev_epoch_graph_off_entity_micro_f1': 0.9828336003662165, 'dev_epoch_graph_off_weighted_f1': 0.9810310744306724, 'dev_epoch_graph_off_loss': 0.08826384510379284, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 8, 'backbone_trainable': True, 'train_loss': 0.042710205563198544, 'dev_entity_macro_precision': 0.9094047570265779, 'dev_entity_macro_recall': 0.9228857564220365, 'dev_entity_macro_f1': 0.9069237136685077, 'dev_entity_micro_f1': 0.9837491416800183, 'dev_weighted_f1': 0.982359946885864, 'dev_loss': 0.0988183076819405, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 0.971702276304729, 'dev_graph_residual_norm': 18.42209628734257, 'dev_layer1_attention_entropy': 0.3049469131231308, 'dev_layer1_attention_variance': 0.07561464980244637, 'dev_layer2_attention_entropy': 0.17175499439239503, 'dev_layer2_attention_variance': 0.09084894090890884, 'dev_epoch_graph_off_entity_macro_precision': 0.9089384216933567, 'dev_epoch_graph_off_entity_macro_recall': 0.9207840916581032, 'dev_epoch_graph_off_entity_macro_f1': 0.903932577146432, 'dev_epoch_graph_off_entity_micro_f1': 0.980544747081712, 'dev_epoch_graph_off_weighted_f1': 0.978845692069413, 'dev_epoch_graph_off_loss': 0.08846828051260673, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 9, 'backbone_trainable': True, 'train_loss': 0.038341667283748396, 'dev_entity_macro_precision': 0.919183398782596, 'dev_entity_macro_recall': 0.9366324385592146, 'dev_entity_macro_f1': 0.9250333117832817, 'dev_entity_micro_f1': 0.9837491416800183, 'dev_weighted_f1': 0.9821483983147326, 'dev_loss': 0.10003194206161424, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0385767626254299, 'dev_graph_residual_norm': 19.709211567619583, 'dev_layer1_attention_entropy': 0.29679596990346907, 'dev_layer1_attention_variance': 0.07673694431781769, 'dev_layer2_attention_entropy': 0.16009676441550255, 'dev_layer2_attention_variance': 0.09255739018321037, 'dev_epoch_graph_off_entity_macro_precision': 0.919732944363393, 'dev_epoch_graph_off_entity_macro_recall': 0.9248877124216519, 'dev_epoch_graph_off_entity_macro_f1': 0.9139983355987594, 'dev_epoch_graph_off_entity_micro_f1': 0.9819180590524147, 'dev_epoch_graph_off_weighted_f1': 0.9801203245807523, 'dev_epoch_graph_off_loss': 0.08540376932360232, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 10, 'backbone_trainable': True, 'train_loss': 0.036027827842990516, 'dev_entity_macro_precision': 0.915297241944508, 'dev_entity_macro_recall': 0.9319004829220248, 'dev_entity_macro_f1': 0.9201619515619952, 'dev_entity_micro_f1': 0.9823758297093156, 'dev_weighted_f1': 0.9806639700531627, 'dev_loss': 0.1037182137259515, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1122145036630928, 'dev_graph_residual_norm': 21.10874803548326, 'dev_layer1_attention_entropy': 0.297821387052536, 'dev_layer1_attention_variance': 0.07649330213665963, 'dev_layer2_attention_entropy': 0.1840619620680809, 'dev_layer2_attention_variance': 0.08904446214437485, 'dev_epoch_graph_off_entity_macro_precision': 0.9185793730311693, 'dev_epoch_graph_off_entity_macro_recall': 0.9212047713528327, 'dev_epoch_graph_off_entity_macro_f1': 0.914670062570912, 'dev_epoch_graph_off_entity_micro_f1': 0.9800869764248111, 'dev_epoch_graph_off_weighted_f1': 0.9781843628665495, 'dev_epoch_graph_off_loss': 0.09094114036881365, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 11, 'backbone_trainable': True, 'train_loss': 0.026513157319641323, 'dev_entity_macro_precision': 0.9075085033558259, 'dev_entity_macro_recall': 0.9232913111104486, 'dev_entity_macro_f1': 0.9101744357373646, 'dev_entity_micro_f1': 0.9832913710231174, 'dev_weighted_f1': 0.9812492124917475, 'dev_loss': 0.10778478463878854, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.0556352369932247, 'dev_graph_residual_norm': 20.020716968197835, 'dev_layer1_attention_entropy': 0.29168283700942993, 'dev_layer1_attention_variance': 0.07710769206285477, 'dev_layer2_attention_entropy': 0.18043946355581283, 'dev_layer2_attention_variance': 0.08950610369443894, 'dev_epoch_graph_off_entity_macro_precision': 0.9219202294972918, 'dev_epoch_graph_off_entity_macro_recall': 0.9168836875109072, 'dev_epoch_graph_off_entity_macro_f1': 0.9106247863588356, 'dev_epoch_graph_off_entity_micro_f1': 0.9810025177386129, 'dev_epoch_graph_off_weighted_f1': 0.9789470683837217, 'dev_epoch_graph_off_loss': 0.08875988552637865, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 12, 'backbone_trainable': True, 'train_loss': 0.020079614142814534, 'dev_entity_macro_precision': 0.9258613990157948, 'dev_entity_macro_recall': 0.9410104935422522, 'dev_entity_macro_f1': 0.9318032401040396, 'dev_entity_micro_f1': 0.9842069123369191, 'dev_weighted_f1': 0.9827786858109236, 'dev_loss': 0.09059755524853244, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1372726343652924, 'dev_graph_residual_norm': 21.56152715098389, 'dev_layer1_attention_entropy': 0.2918229416012764, 'dev_layer1_attention_variance': 0.07716528818011284, 'dev_layer2_attention_entropy': 0.17725868076086043, 'dev_layer2_attention_variance': 0.08988518103957176, 'dev_epoch_graph_off_entity_macro_precision': 0.9176401038641168, 'dev_epoch_graph_off_entity_macro_recall': 0.9311576050993386, 'dev_epoch_graph_off_entity_macro_f1': 0.9209108035021217, 'dev_epoch_graph_off_entity_micro_f1': 0.9823758297093156, 'dev_epoch_graph_off_weighted_f1': 0.9806534292501368, 'dev_epoch_graph_off_loss': 0.07708899686927907, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 13, 'backbone_trainable': True, 'train_loss': 0.018134757275911396, 'dev_entity_macro_precision': 0.9159892838746023, 'dev_entity_macro_recall': 0.9284033143521384, 'dev_entity_macro_f1': 0.916806614142199, 'dev_entity_micro_f1': 0.9842069123369191, 'dev_weighted_f1': 0.9822224728024008, 'dev_loss': 0.10327431707381038, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1555147788151223, 'dev_graph_residual_norm': 21.90911921076238, 'dev_layer1_attention_entropy': 0.2956461200118065, 'dev_layer1_attention_variance': 0.07673069253563881, 'dev_layer2_attention_entropy': 0.17418364256620408, 'dev_layer2_attention_variance': 0.09038243681192398, 'dev_epoch_graph_off_entity_macro_precision': 0.9221394533528164, 'dev_epoch_graph_off_entity_macro_recall': 0.9234170862364609, 'dev_epoch_graph_off_entity_macro_f1': 0.9154208089552074, 'dev_epoch_graph_off_entity_micro_f1': 0.9823758297093156, 'dev_epoch_graph_off_weighted_f1': 0.9804014688908129, 'dev_epoch_graph_off_loss': 0.08525893458747305, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6 see…

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

{'epoch': 14, 'backbone_trainable': True, 'train_loss': 0.01905614588795288, 'dev_entity_macro_precision': 0.9124095870026048, 'dev_entity_macro_recall': 0.9257665545542169, 'dev_entity_macro_f1': 0.9125651257459221, 'dev_entity_micro_f1': 0.9846646829938202, 'dev_weighted_f1': 0.9825789169129793, 'dev_loss': 0.10122916508524213, 'dev_graph_alpha': 0.5, 'dev_graph_residual_base_ratio': 1.1150790575247673, 'dev_graph_residual_norm': 21.13035523466091, 'dev_layer1_attention_entropy': 0.29346218675374985, 'dev_layer1_attention_variance': 0.07696499034762383, 'dev_layer2_attention_entropy': 0.17589260518550873, 'dev_layer2_attention_variance': 0.09021608173847198, 'dev_epoch_graph_off_entity_macro_precision': 0.9193427379063556, 'dev_epoch_graph_off_entity_macro_recall': 0.922151016894817, 'dev_epoch_graph_off_entity_macro_f1': 0.9128773804275192, 'dev_epoch_graph_off_entity_micro_f1': 0.9823758297093156, 'dev_epoch_graph_off_weighted_f1': 0.980420584511873, 'dev_epoch_graph_off_loss': 0.08425138550635893, 'dev_epoch_graph_off_graph_alpha': 0.5, 'dev_epoch_graph_off_graph_residual_base_ratio': nan, 'dev_epoch_graph_off_graph_residual_norm': nan, 'dev_epoch_graph_off_layer1_attention_entropy': nan, 'dev_epoch_graph_off_layer1_attention_variance': nan, 'dev_epoch_graph_off_layer2_attention_entropy': nan, 'dev_epoch_graph_off_layer2_attention_variance': nan}

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

stage                                                 five_seed_retrain_from_scratch
configuration                              latest_frozen_a050_b035_five_seed_retrain
model                              layoutlmv3_split_head_symbolic_rel_gatv2_fusio...
seed                                                                             123
graph_alpha                                                                      0.5
base_aux_weight                                                                 0.35
patience                                                                           6
checkpoint                         /kaggle/working/receipt_kie_five_seed_retrain_...
source                                                          trained_from_scratch
initialization                     pretrained_layoutlmv3_plus_random_graph_no_war...
backbone_lr                                                                  0.00001
head_lr                                                                       0.0001
graph_lr                                                                      0.0002
epochs_ran                                                                        14
best_epoch                                                                        12
total_parameters                                                           132271357
trainable_parameters                                                       132271357
wall_seconds                                                             2168.612316
diagnostic_seconds                                                         29.902968
peak_vram_gb                                                                4.401669
dev_shuffled_entity_macro_f1                                                0.916326
dev_self_loop_entity_macro_f1                                               0.925219
dev_graph_off_entity_macro_f1                                               0.920911
dev_original_minus_shuffled_pp                                              1.547733
dev_original_minus_self_loop_pp                                             0.658381
dev_graph_contribution_pp                                                   1.089244
dev_entity_macro_precision                                                  0.925861
dev_entity_macro_recall                                                      0.94101
dev_entity_macro_f1                                                         0.931803
dev_entity_micro_f1                                                         0.984207
dev_weighted_f1                                                             0.982779
dev_loss                                                                    0.090595
dev_graph_alpha                                                                  0.5
dev_graph_residual_base_ratio                                               1.137273
dev_graph_residual_norm                                                    21.561537
dev_layer1_attention_entropy                                                0.291823
dev_layer1_attention_variance                                               0.077165
dev_layer2_attention_entropy                                                0.177259
dev_layer2_attention_variance                                               0.089885
dtype: object

,model,seeds,dev_macro_f1_mean,dev_macro_f1_std,dev_graph_off_mean,dev_graph_off_std,best_epoch_mean,best_epoch_std,graph_contribution_pp_mean,graph_contribution_pp_std,original_minus_shuffled_pp_mean,original_minus_shuffled_pp_std,original_minus_self_loop_pp_mean,original_minus_self_loop_pp_std,wall_minutes_mean,graph_evidence_pass,gap_vs_baseline_dev_pp
0,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,5,0.924674,0.004867,0.915211,0.00578,11.2,1.095445,0.94635,0.371304,2.015851,0.438481,0.571516,0.502929,36.180027,True,-0.092552

,seed,best_original_epoch,selected_checkpoint_graph_off_f1,lowest_graph_off_f1,lowest_graph_off_epoch,largest_graph_off_drop,largest_graph_off_drop_epoch,sudden_graph_off_drop_ge_1pp
0,7,12,0.920949,0.111776,1,-0.026949,7,True
1,13,10,0.910274,0.110172,1,-0.006769,11,False
2,42,12,0.915331,0.092872,1,-0.010649,10,True
3,123,12,0.920911,0.092394,1,-0.018483,8,True
4,2026,10,0.908590,0.111253,1,-0.020452,8,True

Loading weights:   0%|          | 0/212 [00:00<?, ?it/s]

LayoutLMv3Model LOAD REPORT from: microsoft/layoutlmv3-base
Key                                | Status     |  |
-----------------------------------+------------+--+-
layoutlmv3.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

document predictions:   0%|          | 0/50 [00:00<?, ?it/s]

document predictions:   0%|          | 0/50 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/212 [00:00<?, ?it/s]

LayoutLMv3Model LOAD REPORT from: microsoft/layoutlmv3-base
Key                                | Status     |  |
-----------------------------------+------------+--+-
layoutlmv3.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

document predictions:   0%|          | 0/50 [00:00<?, ?it/s]

document predictions:   0%|          | 0/50 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/212 [00:00<?, ?it/s]

LayoutLMv3Model LOAD REPORT from: microsoft/layoutlmv3-base
Key                                | Status     |  |
-----------------------------------+------------+--+-
layoutlmv3.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

document predictions:   0%|          | 0/50 [00:00<?, ?it/s]

document predictions:   0%|          | 0/50 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/212 [00:00<?, ?it/s]

LayoutLMv3Model LOAD REPORT from: microsoft/layoutlmv3-base
Key                                | Status     |  |
-----------------------------------+------------+--+-
layoutlmv3.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

document predictions:   0%|          | 0/50 [00:00<?, ?it/s]

document predictions:   0%|          | 0/50 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/212 [00:00<?, ?it/s]

LayoutLMv3Model LOAD REPORT from: microsoft/layoutlmv3-base
Key                                | Status     |  |
-----------------------------------+------------+--+-
layoutlmv3.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

evaluate:   0%|          | 0/50 [00:00<?, ?it/s]

document predictions:   0%|          | 0/50 [00:00<?, ?it/s]

document predictions:   0%|          | 0/50 [00:00<?, ?it/s]

,split,comparison,seeds,macro_f1_mean,ci95_low,ci95_high,reference_macro_f1,delta_vs_reference_mean,probability_above_reference,bootstrap_documents,bootstrap_repetitions
0,dev_five_seed,hybrid_seed_13_absolute,1,0.904773,0.830757,0.952239,0.9256,-0.020827,0.2620,100,10000
1,dev_five_seed,hybrid_seed_42_absolute,1,0.908189,0.837794,0.959415,0.9256,-0.017411,0.3253,100,10000
2,dev_five_seed,hybrid_seed_2026_absolute,1,0.905260,0.840216,0.957091,0.9256,-0.020340,0.2636,100,10000
3,dev_five_seed,hybrid_seed_7_absolute,1,0.906276,0.834987,0.959645,0.9256,-0.019324,0.3013,100,10000
4,dev_five_seed,hybrid_seed_123_absolute,1,0.915862,0.849098,0.961846,0.9256,-0.009738,0.4270,100,10000
5,dev_five_seed,mean_hybrid_across_five_seeds_absolute,5,0.908072,0.843762,0.951024,0.9256,-0.017528,0.2912,100,10000
6,test_five_seed,hybrid_seed_13_absolute,1,0.946679,0.891770,0.978203,0.9233,0.023379,0.8435,100,10000
7,test_five_seed,hybrid_seed_42_absolute,1,0.934653,0.892819,0.964289,0.9233,0.011353,0.7518,100,10000
8,test_five_seed,hybrid_seed_2026_absolute,1,0.908150,0.865763,0.943366,0.9233,-0.015150,0.2288,100,10000
9,test_five_seed,hybrid_seed_7_absolute,1,0.937862,0.892558,0.965826,0.9233,0.014562,0.7972,100,10000
10,test_five_seed,hybrid_seed_123_absolute,1,0.934425,0.891354,0.961828,0.9233,0.011125,0.7752,100,10000
11,test_five_seed,mean_hybrid_across_five_seeds_absolute,5,0.932353,0.889650,0.958707,0.9233,0.009053,0.7493,100,10000

Total five-seed retrain time (min): 192.5704911271731

In [12]:
def mean_std_text(values, digits=4):
    values = pd.Series(values, dtype=float).dropna()
    mean = values.mean()
    if len(values) < 2:
        return f"{mean:.{digits}f} (1 seed)"
    return f"{mean:.{digits}f} ± {values.std(ddof=1):.{digits}f}"


group = results_df
final_summary = configuration_summary(group).iloc[0]
final_table = pd.DataFrame([{
    "Model": MODEL_NAME,
    "Seeds": len(group),
    "Train runs from scratch": len(SEEDS),
    "Dev Entity Macro F1": mean_std_text(group["dev_entity_macro_f1"]),
    "Dev graph-off Macro F1": mean_std_text(
        group["dev_graph_off_entity_macro_f1"]
    ),
    "Test Entity Macro F1": mean_std_text(group["test_entity_macro_f1"]),
    "Test Entity Micro F1": mean_std_text(group["test_entity_micro_f1"]),
    "Test Weighted F1": mean_std_text(group["test_weighted_f1"]),
    "Best epoch": mean_std_text(group["best_epoch"], digits=1),
    "Wall time/run (min)": mean_std_text(
        group["wall_seconds"] / 60, digits=1
    ),
    "Total five-seed time (min)": f"{total_experiment_minutes:.1f}",
    "Peak VRAM (GiB)": mean_std_text(group["peak_vram_gb"], digits=2),
    "Parameters (M)": f"{group['total_parameters'].iloc[0] / 1e6:.2f}",
    "Fixed graph alpha": f"{selected_alpha:.2f}",
    "Base auxiliary weight": f"{selected_base_aux:.2f}",
    "Patience": PATIENCE,
    "Frozen latest architecture": True,
    "Original - shuffled (dev pp)": mean_std_text(
        group["dev_original_minus_shuffled_pp"]
    ),
    "Original - self-loop (dev pp)": mean_std_text(
        group["dev_original_minus_self_loop_pp"]
    ),
    "Graph contribution (dev pp)": mean_std_text(
        group["dev_graph_contribution_pp"]
    ),
}])
final_table.to_csv(ARTIFACT_DIR / "final_results_table.csv", index=False)
print("FINAL TABLE — five seeds retrained from scratch")
display(final_table)

graph_pass = bool(final_summary["graph_evidence_pass"])
dev_gap = BASELINE_DEV_F1 - float(final_summary["dev_macro_f1_mean"])
test_mean = float(group["test_entity_macro_f1"].mean())
collapsed_seeds = group[
    group["dev_graph_off_entity_macro_f1"] < COLLAPSE_THRESHOLD
]["seed"].astype(int).tolist()

if graph_pass and dev_gap < DEV_GAP_LIMIT and test_mean > BASELINE_TEST_MACRO_F1:
    decision_level = "A_supportive_hybrid"
    decision_text = PREDECLARED_DECISION_RULES[
        "rule_A_supportive_hybrid"
    ]["conclusion"]
elif len(collapsed_seeds) >= 2 and not graph_pass:
    decision_level = "B_systematic_base_problem"
    decision_text = PREDECLARED_DECISION_RULES[
        "rule_B_systematic_base_problem"
    ]["conclusion"]
elif dev_gap >= DEV_GAP_LIMIT:
    decision_level = "C_hybrid_not_reliable"
    decision_text = PREDECLARED_DECISION_RULES[
        "rule_C_hybrid_not_reliable"
    ]["conclusion"]
else:
    decision_level = "mixed_inconclusive"
    decision_text = (
        "Five-seed evidence is mixed; report all metrics without a "
        "superiority claim."
    )

test_bootstrap_aggregate = bootstrap_test_df[
    bootstrap_test_df["comparison"].eq(
        "mean_hybrid_across_five_seeds_absolute"
    )
].iloc[0]
decision = {
    "decision_level": decision_level,
    "decision": decision_text,
    "graph_evidence_pass_mean_gt_std": graph_pass,
    "dev_macro_f1_mean": float(final_summary["dev_macro_f1_mean"]),
    "dev_gap_baseline_reference_minus_hybrid": dev_gap,
    "dev_gap_below_0_3pp": bool(dev_gap < DEV_GAP_LIMIT),
    "test_macro_f1_mean": test_mean,
    "test_above_reported_baseline_mean": bool(
        test_mean > BASELINE_TEST_MACRO_F1
    ),
    "test_absolute_bootstrap_ci95_low": float(
        test_bootstrap_aggregate["ci95_low"]
    ),
    "test_absolute_bootstrap_ci95_high": float(
        test_bootstrap_aggregate["ci95_high"]
    ),
    "collapse_threshold": COLLAPSE_THRESHOLD,
    "collapsed_seeds": collapsed_seeds,
    "graph_contribution_pp_mean": float(
        final_summary["graph_contribution_pp_mean"]
    ),
    "graph_contribution_pp_std": float(
        final_summary["graph_contribution_pp_std"]
    ),
    "publication_limitation": (
        "No baseline checkpoint is available. Baseline comparisons use only "
        "previously reported aggregate means and are not paired bootstrap "
        "comparisons. Strict superiority is therefore not claimed."
    ),
}
(ARTIFACT_DIR / "predeclared_decision_outcome.json").write_text(
    json.dumps(decision, ensure_ascii=False, indent=2), encoding="utf-8"
)
print("PREDECLARED DECISION OUTCOME")
display(pd.Series(decision))

comparison_table = pd.DataFrame([
    {
        "Stage": "Baseline Word-CRF (reported 3 seeds)",
        "Dev Entity Macro F1": "0.9256 ± 0.0100",
        "Test Entity Macro F1": "0.9233 ± 0.0207",
        "Graph contribution (dev pp)": "—",
    },
    {
        "Stage": "Latest split-head (previous 3 seeds)",
        "Dev Entity Macro F1": "0.9241 ± 0.0061",
        "Test Entity Macro F1": "0.9460 ± 0.0111",
        "Graph contribution (dev pp)": "1.0972 ± 1.1481",
    },
    {
        "Stage": "Frozen split-head retrained from scratch (5 seeds)",
        "Dev Entity Macro F1": mean_std_text(
            group["dev_entity_macro_f1"]
        ),
        "Test Entity Macro F1": mean_std_text(
            group["test_entity_macro_f1"]
        ),
        "Graph contribution (dev pp)": mean_std_text(
            group["dev_graph_contribution_pp"]
        ),
    },
])
comparison_table.to_csv(
    ARTIFACT_DIR / "before_after_comparison.csv", index=False
)
display(comparison_table)

deploy_row = group.loc[group["dev_entity_macro_f1"].idxmax()]
deploy_checkpoint = ARTIFACT_DIR / f"{MODEL_NAME}_best.pt"
shutil.copy2(deploy_row["checkpoint"], deploy_checkpoint)
(ARTIFACT_DIR / "selected_deploy_run.json").write_text(
    json.dumps(
        deploy_row.to_dict(), ensure_ascii=False, indent=2, default=str
    ),
    encoding="utf-8",
)
print("Deploy checkpoint selected by dev F1:", deploy_checkpoint)

FINAL TABLE — five seeds retrained from scratch

,Model,Seeds,Train runs from scratch,Dev Entity Macro F1,Dev graph-off Macro F1,Test Entity Macro F1,Test Entity Micro F1,Test Weighted F1,Best epoch,Wall time/run (min),Total five-seed time (min),Peak VRAM (GiB),Parameters (M),Fixed graph alpha,Base auxiliary weight,Patience,Frozen latest architecture,Original - shuffled (dev pp),Original - self-loop (dev pp),Graph contribution (dev pp)
0,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,5,5,0.9247 ± 0.0049,0.9152 ± 0.0058,0.9398 ± 0.0161,0.9764 ± 0.0037,0.9736 ± 0.0032,11.2 ± 1.1,36.2 ± 0.2,192.6,4.40 ± 0.00,132.27,0.50,0.35,6,True,2.0159 ± 0.4385,0.5715 ± 0.5029,0.9464 ± 0.3713

PREDECLARED DECISION OUTCOME

decision_level                                                           A_supportive_hybrid
decision                                   Hybrid has supportive five-seed evidence; pair...
graph_evidence_pass_mean_gt_std                                                         True
dev_macro_f1_mean                                                                   0.924674
dev_gap_baseline_reference_minus_hybrid                                             0.000926
dev_gap_below_0_3pp                                                                     True
test_macro_f1_mean                                                                    0.9398
test_above_reported_baseline_mean                                                       True
test_absolute_bootstrap_ci95_low                                                     0.88965
test_absolute_bootstrap_ci95_high                                                   0.958707
collapse_threshold                                                                    0.9106
collapsed_seeds                                                                   [13, 2026]
graph_contribution_pp_mean                                                           0.94635
graph_contribution_pp_std                                                           0.371304
publication_limitation                     No baseline checkpoint is available. Baseline ...
dtype: object

,Stage,Dev Entity Macro F1,Test Entity Macro F1,Graph contribution (dev pp)
0,Baseline Word-CRF (reported 3 seeds),0.9256 ± 0.0100,0.9233 ± 0.0207,—
1,Latest split-head (previous 3 seeds),0.9241 ± 0.0061,0.9460 ± 0.0111,1.0972 ± 1.1481
2,Frozen split-head retrained from scratch (5 se...,0.9247 ± 0.0049,0.9398 ± 0.0161,0.9464 ± 0.3713

Deploy checkpoint selected by dev F1: /kaggle/working/receipt_kie_five_seed_retrain_artifacts/layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_best.pt

## 8. Per-Class Performance Analysis

This section aggregates precision, recall, F1, and support for each receipt entity across the five seeds. Sorting classes by mean F1 highlights low-support and difficult fields that may not be visible in aggregate macro and micro scores.

In [13]:
per_class_rows = []
for run_key, split_reports in reports.items():
    model_name, seed_text = run_key.rsplit("_seed", 1)
    test_report = split_reports["test"]
    for label in LABELS[1:]:
        values = test_report.get(label, {})
        per_class_rows.append({
            "model": model_name,
            "seed": int(seed_text),
            "label": label,
            "precision": values.get("precision", 0.0),
            "recall": values.get("recall", 0.0),
            "f1": values.get("f1-score", 0.0),
            "support": values.get("support", 0.0),
        })

per_class_df = pd.DataFrame(per_class_rows)
per_class_df.to_csv(ARTIFACT_DIR / "per_class_results_by_seed.csv", index=False)
per_class_summary = per_class_df.groupby(["model", "label"]).agg(
    f1_mean=("f1", "mean"), f1_std=("f1", "std"),
    precision_mean=("precision", "mean"), recall_mean=("recall", "mean"),
    support=("support", "first"), seeds=("seed", "count"),
).reset_index()
per_class_summary.to_csv(ARTIFACT_DIR / "per_class_summary.csv", index=False)

model_class_summary = per_class_summary[
    per_class_summary["model"] == MODEL_NAME
].sort_values("f1_mean")
print("HYBRID CLASSES — weakest first")
display(model_class_summary)

HYBRID CLASSES — weakest first

,model,label,f1_mean,f1_std,precision_mean,recall_mean,support,seeds
4,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-EMONEY_PAYMENT,0.639444,0.183842,0.550000,0.800000,4.0,5
13,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-OTHER,0.766206,0.047321,0.904494,0.673171,41.0,5
6,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-MENUTYPE_CNT,0.844651,0.022769,0.944762,0.764706,17.0,5
0,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-CARD_PAYMENT,0.958088,0.040253,0.953059,0.964706,51.0,5
8,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-MENU_DISCOUNT_PRICE,0.960434,0.019079,0.948145,0.973333,30.0,5
1,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-CASH,0.962312,0.013413,0.979494,0.945946,148.0,5
5,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-MENUQTY_CNT,0.963588,0.009026,0.940322,0.988060,67.0,5
3,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-DISCOUNT,0.971429,0.063888,1.000000,0.950000,16.0,5
12,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-MENU_UNITPRICE,0.975329,0.008231,0.976889,0.973913,69.0,5
7,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-MENU_CNT,0.980376,0.007030,0.968500,0.992683,246.0,5
2,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-CHANGE,0.980408,0.004403,0.961598,1.000000,120.0,5
11,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-MENU_PRICE,0.980483,0.002431,0.968018,0.993284,268.0,5
17,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-TOTAL,0.980943,0.002986,0.976324,0.985646,209.0,5
15,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-SUBTOTAL,0.984977,0.005534,0.978497,0.991724,145.0,5
9,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-MENU_NM,0.986971,0.003924,0.990474,0.983514,740.0,5
10,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-MENU_NUM,0.990476,0.021296,1.000000,0.981818,11.0,5
14,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-SERVICE,0.992653,0.010925,0.985598,1.000000,40.0,5
16,layoutlmv3_split_head_symbolic_rel_gatv2_fusio...,S-TAX,0.997628,0.005303,1.000000,0.995313,128.0,5

## 9. Checkpoints, Metadata, and Reproducibility Artifacts

This section packages the complete hybrid experiment, including:

- The deployment checkpoint selected by development Entity Macro F1.
- Per-seed checkpoints and training histories.
- Final aggregate results and per-seed experiment tables.
- Development ablation results for all four graph conditions.
- Attention, residual, and graph-off diagnostics.
- Per-class reports and document-level predictions.
- Absolute bootstrap results and predeclared decision records.
- Model configuration, seed list, initialization policy, selection protocol, and environment metadata.

The downloadable archive is written to `/kaggle/working/receipt_kie_five_seed_retrain_artifacts_download.zip`.

In [14]:
archive_base = ARTIFACT_DIR.parent / f"{ARTIFACT_DIR.name}_download"
metadata = {
    "task": "CORD receipt key information extraction",
    "architecture": (
        "Frozen latest: LayoutLMv3 + 2-layer symbolic-line Relation-GATv2 + "
        "separate base/fusion classifiers + hidden fusion + Word-CRF"
    ),
    "model_id": CFG.model_id,
    "model_revision": CFG.model_revision,
    "seeds_trained_from_scratch": SEEDS,
    "selected_graph_alpha": selected_alpha,
    "selected_base_aux_weight": selected_base_aux,
    "patience": PATIENCE,
    "bootstrap_repetitions": CFG.bootstrap_repetitions,
    "test_policy": (
        "test evaluated only after all five seeds completed training and "
        "all four dev ablations"
    ),
    "checkpoint_selection": "dev entity macro F1 original mode only",
    "warm_start": False,
    "old_checkpoints_reused": False,
    "architecture_changed_from_latest": False,
    "graph_construction_changed": False,
    "train_runs": len(SEEDS),
    "artifact_dir": str(ARTIFACT_DIR),
    "deploy_checkpoint": str(deploy_checkpoint),
    "download_archive": f"{archive_base}.zip",
}
(ARTIFACT_DIR / "run_metadata.json").write_text(
    json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8"
)
display(pd.Series(metadata))
archive_path = shutil.make_archive(
    str(archive_base), "zip", root_dir=ARTIFACT_DIR
)
print("Download archive:", archive_path)
print("Saved artifacts:")
for path in sorted(ARTIFACT_DIR.iterdir()):
    print(path.name)

task                                          CORD receipt key information extraction
architecture                        Frozen latest: LayoutLMv3 + 2-layer symbolic-l...
model_id                                                    microsoft/layoutlmv3-base
model_revision                                                                   main
seeds_trained_from_scratch                                     [13, 42, 2026, 7, 123]
selected_graph_alpha                                                              0.5
selected_base_aux_weight                                                         0.35
patience                                                                            6
bootstrap_repetitions                                                           10000
test_policy                         test evaluated only after all five seeds compl...
checkpoint_selection                           dev entity macro F1 original mode only
warm_start                                                                      False
old_checkpoints_reused                                                          False
architecture_changed_from_latest                                                False
graph_construction_changed                                                      False
train_runs                                                                          5
artifact_dir                        /kaggle/working/receipt_kie_five_seed_retrain_...
deploy_checkpoint                   /kaggle/working/receipt_kie_five_seed_retrain_...
download_archive                    /kaggle/working/receipt_kie_five_seed_retrain_...
dtype: object

Download archive: /kaggle/working/receipt_kie_five_seed_retrain_artifacts_download.zip
Saved artifacts:
before_after_comparison.csv
bootstrap_hybrid_absolute_results.csv
classification_reports.json
dev_ablation_results.csv
dev_configuration_summary.csv
document_predictions.json
epoch_graph_off_diagnostics.csv
experiment_results.csv
final_results_table.csv
latest_frozen_a050_b035_five_seed_retrain_seed_cache.csv
layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_best.pt
layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6_seed123.pt
layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6_seed123_history.csv
layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6_seed13.pt
layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6_seed13_history.csv
layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6_seed2026.pt
layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6_seed2026_history.csv
layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6_seed42.pt
layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6_seed42_history.csv
layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6_seed7.pt
layoutlmv3_split_head_symbolic_rel_gatv2_fusion_crf_latest_frozen_a050_b035_five_seed_retrain_a050_b035_p6_seed7_history.csv
per_class_results_by_seed.csv
per_class_summary.csv
predeclared_decision_outcome.json
predeclared_decision_rules.json
run_metadata.json
selected_deploy_run.json

## 10. Interpretation and Reporting Scope

The final results should distinguish three claims:

1. **Predictive performance:** report development and test Entity Macro F1 as mean ± sample standard deviation across the five independent seeds.
2. **Graph contribution:** report the original-minus-shuffled, original-minus-self-loop, and original-minus-graph-off differences on the development split.
3. **Uncertainty:** use the saved document-level bootstrap intervals as an absolute uncertainty analysis for the hybrid model.

The baseline comparison uses aggregate metrics rather than matched per-document predictions. Therefore, the experiment supports descriptive comparison with the baseline but does not constitute a paired statistical superiority test. A paired comparison would require baseline predictions or checkpoints evaluated on the same documents and corresponding seeds.

Because the notebook uses reference CORD text and bounding boxes, it evaluates key information extraction with oracle OCR inputs rather than a complete OCR-to-extraction pipeline.